(function(g){var window=this;'use strict';var r$=function(d){d.publish("cardstatechange",d.Tv()&&d.D7()?1:0)},tN=function(d,q){var T=g.ej(q),Y=T?q:arguments;
for(T=T?0:1;T<Y.length;T++){if(d==null)return;d=d[Y[T]]}return d},TYE=function(d){var q=g.lY(d);
d=g.Vp(d);return new g.WB(q.x,q.y,d.width,d.height)},YSl=function(d,q,T){var Y=Y===void 0?{}:Y;
var e;return e=g.yi(d,q,function(){g.hB(e);T.apply(d,arguments)},Y)},Gw=function(d){d=g.X_(d);
delete BS[d];g.FV(BS)&&Kf&&Kf.stop()},Ubq=function(){Kf||(Kf=new g.f9(function(){e1s()},20));
var d=Kf;d.isActive()||d.start()},e1s=function(){var d=g.F_();
g.os(BS,function(q){b$s(q,d)});
g.FV(BS)||Ubq()},Lf=function(d,q,T,Y){g.UA.call(this);
if(!Array.isArray(d)||!Array.isArray(q))throw Error("Start and end parameters must be arrays");if(d.length!=q.length)throw Error("Start and end points must be the same length");this.U=d;this.L=q;this.duration=T;this.S=Y;this.coords=[];this.progress=this.X=0;this.T=null},b$s=function(d,q){q<d.startTime&&(d.endTime=q+d.endTime-d.startTime,d.startTime=q);
d.progress=(q-d.startTime)/(d.endTime-d.startTime);d.progress>1&&(d.progress=1);d.X=1E3/(q-d.T);d.T=q;XEl(d,d.progress);d.progress==1?(d.G=0,Gw(d),d.onFinish(),d.YG()):d.isPlaying()&&d.OT()},XEl=function(d,q){typeof d.S==="function"&&(q=d.S(q));
d.coords=Array(d.U.length);for(var T=0;T<d.U.length;T++)d.coords[T]=(d.L[T]-d.U[T])*q+d.U[T]},JAI=function(d,q){g.fb.call(this,d);
this.coords=q.coords;this.x=q.coords[0];this.y=q.coords[1];this.z=q.coords[2];this.duration=q.duration;this.progress=q.progress;this.fps=q.X;this.state=q.G},kd=function(d,q,T,Y,e){Lf.call(this,q,T,Y,e);
this.element=d},s4B=function(d,q,T,Y,e){if(q.length!=2||T.length!=2)throw Error("Start and end points must be 2D");
kd.call(this,d,q,T,Y,e)},$bR=function(d){return Math.pow(d,3)},gjn=function(d){return 3*d*d-2*d*d*d},FTB=function(d){g.W.call(this);
this.U=d||window;this.G=[]},PS=function(d){return d.baseUrl||null},WS=function(d,q){return g.Zl(g.yC(d,q),function(T){return!!T})},NYc=function(d,q,T){function Y(x2){var JY=x2.hovercardButton;
if(!JY)return null;JY=JY.subscribeButtonRenderer;if(!JY)return null;var s6=U(JY.unsubscribedButtonText),qH=U(JY.subscribedButtonText);if(JY.subscribed){var O6=U(JY.subscriberCountWithUnsubscribeText);var SD=U(JY.subscriberCountText)}else O6=U(JY.subscriberCountText),SD=U(JY.subscriberCountWithSubscribeText);var dL=null;if(x2.signinEndpoint){dL=tN(x2,"signinEndpoint","webNavigationEndpointData","url");if(!dL){var hE,JE;dL=(JE=g.D((hE=JY.signInEndpoint)==null?void 0:hE.commandMetadata,g.AX))==null?
void 0:JE.url}if(!dL)return null}return s6&&(qH||dL)?{subscribed:JY.subscribed,subscribeText:s6,subscribeCount:O6,unsubscribeText:qH,unsubscribeCount:SD,enabled:JY.enabled,signinUrl:dL,classic:x2.useClassicSubscribeButton}:null}
function e(x2){if(x2){var JY=[],s6=x2.videoId;s6&&JY.push("v="+s6);(s6=x2.playlistId)&&JY.push("list="+s6);(x2=x2.startTimeSeconds)&&JY.push("t="+x2);return"/watch?"+JY.join("&")}}
function U(x2){if(!x2)return null;var JY=x2.simpleText;return JY?JY:x2.runs?g.yC(x2.runs,function(s6){return s6.text}).join(""):null}
q=q.endscreenElementRenderer;if(!q)return null;var b=q.style,J=q.endpoint||{},F=null,N=null,R=!1,x=null,y=null,h=null,H=null,a=!1,p=null,t=null,n=null,K=null,P=null,w=null;if(b==="VIDEO")g.D(J,g.KM)?F=g.D(J,g.KM).url:(w=g.D(J,g.EB),F=e(w)),N=!1,x=d,q.thumbnailOverlays?(R=q.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,y=U(R.text),R=R.style==="LIVE"):y=U(q.videoDuration);else if(b==="PLAYLIST")g.D(J,g.KM)?F=g.D(J,g.KM).url:(w=g.D(J,g.EB),F=e(w)),N=!1,x=d,h=U(q.playlistLength);else if(b===
"CHANNEL"){if(a=tN(J,"browseEndpoint","browseId"))H=a,F="/channel/"+H;N=!1;x="new";(a=!!q.isSubscribe)?p=Y(q):t=U(q.subscribersText)}else b==="WEBSITE"?((n=tN(J,"urlEndpoint","url"))&&(F=n),N=!0,x="new",n=q.icon.thumbnails[0].url):b==="CREATOR_MERCHANDISE"&&(q.productPrice&&(K=U(q.productPrice)),q.additionalFeesText&&(P=U(q.additionalFeesText)),(N=tN(J,"urlEndpoint","url"))&&(F=N),N=!0,x="new");d=tN(q,"title","accessibility","accessibilityData","label");var l=q.endpoint?q.endpoint.clickTrackingParams:
null,m="";if(q.metadata){var b_=U(q.metadata);b_&&(m=b_)}return{id:"element-"+T,type:b,title:U(q.title),metadata:m,callToAction:U(q.callToAction),ew:q.image,iconUrl:n,left:Number(q.left),width:Number(q.width),top:Number(q.top),aspectRatio:Number(q.aspectRatio),startMs:Math.floor(Number(q.startMs)),endMs:Math.floor(Number(q.endMs)),videoDuration:y,cS:R,playlistLength:h,channelId:H,subscribeButton:p,subscribersText:t,isSubscribe:a,targetUrl:F||null,aH:N,sessionData:l?{itct:l}:null,hfU:x,z_:d?d:null,
isPlaceholder:q.isPlaceholder,impressionUrls:WS(q.impressionUrls||[],PS),jl:WS(q.hovercardShowUrls||[],PS),clickUrls:WS(J.loggingUrls||[],PS),visualElement:g.y0(q.trackingParams),productPrice:K,additionalFeesText:P,watchEndpoint:w||null}},R1R=function(d,q){var T={startMs:Math.floor(Number(d.startMs)),
impressionUrls:WS(d.impressionUrls||[],PS),elements:WS(d.elements||[],function(Y,e){return NYc(q,Y,e)})};
d.trackingParams&&(T.visualElement=g.y0(d.trackingParams));return T},xbN=function(d){g.na.call(this,d);
this.T=this.endscreen=null;this.U={};this.X={};this.S=this.j=null;this.B=[];this.G=null;this.lr=!0;this.L=0;d=d.C();this.K=g.bS(d)||g.JJ(d);this.events=new g.aI(this);g.C(this,this.events);this.events.W(this.player,g.Sh("creatorendscreen"),this.onCueRangeEnter);this.events.W(this.player,g.lG("creatorendscreen"),this.onCueRangeExit);this.events.W(this.player,"resize",this.gz);this.events.W(window,"focus",this.hUk);this.load();var q=g.FE("STYLE");(g.YE("HEAD")[0]||document.body).appendChild(q);this.addOnDisposeCallback(function(){g.h4(q)});
q.sheet&&(q.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),q.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},yAn=function(d){return d.player.getVideoData().kc?"current":d.K?"new":"current"},Cf=function(d){return d.player.C().playerStyle==="creator-endscreen-editor"},h1Q=function(d){var q=d.player.getVideoData(),T=q.videoId;
d.T&&d.T.abort();T={method:"POST",onFinish:function(e){var U=d.T=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),U=JSON.parse(e),U=R1R(U,yAn(d))));uJ(d,U)},
urlParams:{v:T},withCredentials:!0};d.K&&(T.urlParams.ptype="embedded");var Y=q.b4;Y&&(T.postParams={ad_tracking:Y});if(q=g.m66(q))if(q=g.b4(q),q=g.YS(q))d.T=g.QB(q,T)},uJ=function(d,q,T){T=T===void 0?!0:T;
d.player.hm("creatorendscreen");d.j&&(d.j.dispose(),d.j=null,d.S.dispose(),d.S=null);for(var Y=g.E(Object.values(d.U)),e=Y.next();!e.done;e=Y.next())e.value.dispose();d.U={};d.X={};d.B.length>0&&(d.B.forEach(function(J){J.dispose()}),d.B.length=0);
d.G&&(g.TR(d.G,"ytp-ce-element-show"),d.G.setAttribute("aria-hidden","true"));d.L=0;if((d.endscreen=q)&&q.elements){T&&H$_(d);T=[];Y=new g.Ij(q.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});T.push(Y);d.player.C().U||(d.j=new g.f({Y:"div",D:"ytp-ce-shadow"}),g.o6(d.player,d.j.element,4),d.S=new g.oh(d.j,200));for(Y=0;Y<q.elements.length;++Y){e=q.elements[Y];var U=Q4L(d,e);if(U){d.U[e.id]=U;d.X[e.id]=e;g.o6(d.player,U.element,4);var b=new g.Ij(e.startMs,e.endMs,{id:"ytp-ce-element-"+
e.id,namespace:"creatorendscreen"});T.push(b);MEI(d,U,e)}else g.OL(new g.CW("buildEndscreenElement null",e))}d.player.ES(T);d.gz()}},H$_=function(d){var q=g.Ha(),T=g.Q0();
T&&q&&d.endscreen.visualElement&&g.iF(g.un)(void 0,T,q,d.endscreen.visualElement)},Q4L=function(d,q){var T=null;
switch(q.type){case "VIDEO":d={Y:"div",hF:["ytp-ce-element","ytp-ce-video"],Z:{tabindex:"0","aria-label":q.z_||"","aria-hidden":"true"},V:[{Y:"div",D:"ytp-ce-element-shadow"},{Y:"div",D:"ytp-ce-covering-image",Z:Do(q)},{Y:"div",D:"ytp-ce-covering-shadow-top"},{Y:"a",D:"ytp-ce-covering-overlay",Z:{href:w$(d,q.targetUrl),tabindex:"-1"},V:[{Y:"div",hF:["ytp-ce-video-title","ytp-webkit-ellipsis"],Z:{dir:g.$G(q.title||"")},j5:q.title},{Y:"div",D:q.cS?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
j5:q.videoDuration||void 0}]}]};T=new g.f(d);break;case "PLAYLIST":d={Y:"div",hF:["ytp-ce-element","ytp-ce-playlist"],Z:{tabindex:"0","aria-label":q.z_||"","aria-hidden":"true"},V:[{Y:"div",D:"ytp-ce-element-shadow"},{Y:"div",D:"ytp-ce-covering-image",Z:Do(q)},{Y:"div",D:"ytp-ce-covering-shadow-top"},{Y:"a",D:"ytp-ce-covering-overlay",Z:{href:w$(d,q.targetUrl),tabindex:"-1"},V:[{Y:"div",hF:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Z:{dir:g.$G(q.title||"")},j5:q.title},{Y:"div",D:"ytp-ce-playlist-count",
V:[{Y:"div",D:"ytp-ce-playlist-icon"},{Y:"div",D:"ytp-ce-playlist-count-text",j5:q.playlistLength||void 0}]}]}]};T=new g.f(d);break;case "CHANNEL":T={Y:"div",hF:["ytp-ce-element","ytp-ce-channel",q.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Z:{tabindex:"0","aria-label":q.z_||"","aria-hidden":"true"},V:[{Y:"div",D:"ytp-ce-element-shadow"},{Y:"div",D:"ytp-ce-expanding-overlay",V:[{Y:"div",D:"ytp-ce-expanding-overlay-hider"},{Y:"div",D:"ytp-ce-expanding-overlay-background"},{Y:"div",D:"ytp-ce-expanding-overlay-content",
V:[{Y:"div",D:"ytp-ce-expanding-overlay-body",V:[{Y:"div",D:"ytp-ce-expanding-overlay-body-padding",V:[{Y:"a",hF:["ytp-ce-channel-title","ytp-ce-link"],Z:{href:w$(d,q.targetUrl),target:"_blank",tabindex:"-1",dir:g.$G(q.title||"")},j5:q.title},q.subscribeButton?{Y:"div",D:"ytp-ce-subscribe-container",V:[{Y:"div",D:"ytp-ce-channel-subscribe"}]}:"",q.subscribersText?{Y:"div",D:"ytp-ce-channel-subscribers-text",j5:q.subscribersText}:"",q.metadata?{Y:"div",hF:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],j5:q.metadata}:""]}]}]}]},{Y:"div",D:"ytp-ce-expanding-image",Z:Do(q)}]};T=new g.f(T);var Y=g.UM(document,"div","ytp-ce-channel-subscribe",T.element)[0];if(q.subscribeButton&&q.channelId){g.d9(Y,"ytp-ce-subscribe-button");if(d.player.C().U){var e=null;var U=q.sessionData.itct}else e="endscreen",U=null;e=new g.Jg(q.subscribeButton.subscribeText,q.subscribeButton.subscribeCount,q.subscribeButton.unsubscribeText,q.subscribeButton.unsubscribeCount,!!q.subscribeButton.enabled,!!q.subscribeButton.classic,
q.channelId,!!q.subscribeButton.subscribed,e,U,d.player,!1);Y.appendChild(e.element);d.B.push(e)}break;case "WEBSITE":d={Y:"div",hF:["ytp-ce-element","ytp-ce-website"],Z:{tabindex:"0","aria-label":q.z_||"","aria-hidden":"true"},V:[{Y:"div",D:"ytp-ce-element-shadow"},{Y:"div",D:"ytp-ce-expanding-overlay",V:[{Y:"div",D:"ytp-ce-expanding-overlay-hider"},{Y:"div",D:"ytp-ce-expanding-overlay-background"},{Y:"div",D:"ytp-ce-expanding-overlay-content",V:[{Y:"div",D:"ytp-ce-expanding-overlay-body",V:[{Y:"div",
D:"ytp-ce-expanding-overlay-body-padding",V:[{Y:"div",D:"ytp-ce-website-title",Z:{dir:g.$G(q.title||"")},j5:q.title},{Y:"div",D:"ytp-ce-website-metadata",j5:q.metadata},{Y:"a",hF:["ytp-ce-website-goto","ytp-ce-link"],Z:{href:w$(d,q.targetUrl),target:"_blank",tabindex:"-1"},j5:q.callToAction}]}]}]}]},{Y:"div",D:"ytp-ce-expanding-image",Z:Do(q)},{Y:"div",D:"ytp-ce-expanding-icon",Z:cAj(q.iconUrl)}]};T=new g.f(d);break;case "CREATOR_MERCHANDISE":T="",q.productPrice&&(T={Y:"div",D:"ytp-ce-merchandise-price-container",
V:[{Y:"div",D:"ytp-ce-merchandise-price",j5:q.productPrice}]},q.additionalFeesText&&T.V.push({Y:"div",D:"ytp-ce-merchandise-additional-fees",j5:q.additionalFeesText})),d={Y:"div",hF:["ytp-ce-element","ytp-ce-merchandise"],Z:{tabindex:"0","aria-label":q.z_||"","aria-hidden":"true"},V:[{Y:"div",D:"ytp-ce-element-shadow"},{Y:"div",D:"ytp-ce-expanding-overlay",V:[{Y:"div",D:"ytp-ce-expanding-overlay-hider"},{Y:"div",D:"ytp-ce-expanding-overlay-background"},{Y:"div",D:"ytp-ce-expanding-overlay-content",
V:[{Y:"div",D:"ytp-ce-expanding-overlay-body",V:[{Y:"div",D:"ytp-ce-expanding-overlay-body-padding",V:[{Y:"div",D:"ytp-ce-merchandise-title",Z:{dir:g.$G(q.title||"")},j5:q.title},T,{Y:"div",D:"ytp-ce-merchandise-metadata",j5:q.metadata},{Y:"a",hF:["ytp-ce-merchandise-goto","ytp-ce-link"],Z:{href:w$(d,q.targetUrl),target:"_blank",tabindex:"-1"},j5:q.callToAction}]}]}]}]},{Y:"div",D:"ytp-ce-expanding-image",Z:Do(q)},{Y:"div",D:"ytp-ce-merchandise-invideo-cta-container",V:[{Y:"div",D:"ytp-ce-merchandise-invideo-cta",
j5:q.callToAction||void 0}]}]},T=new g.f(d)}q.isPlaceholder&&g.d9(T.element,"ytp-ce-placeholder");return T},Do=function(d){if(d.ew)var q=d.ew.thumbnails;
return cAj(q?q[q.length-1].url:null)},cAj=function(d){return d?{style:"background-image: url("+d+")"}:{}},MEI=function(d,q,T){function Y(F){F&&(q.listen("blur",function(){F.style.display!="none"&&d.lr&&F.focus()}),q.W(F,"focus",U),q.W(F,"blur",b))}
function e(F){d.L+=F;d.L>0?(g.d9(q.element,"ytp-ce-force-expand"),ff(d,T.id,!0)):(g.TR(q.element,"ytp-ce-force-expand"),g.TR(q.element,"ytp-ce-element-hover"),ff(d,T.id,!1))}
function U(){e(1)}
function b(){e(-1)}
q.listen("mouseenter",function(){EjR(d,q,T)});
q.listen("mouseleave",function(){j4R(d,q,T)});
d.player.C().U||q.listen("click",function(){g.d9(q.element,"ytp-ce-element-hover")});
q.listen("click",function(F){aYQ(d,T,F)});
q.listen("keypress",function(F){aYQ(d,T,F)});
q.listen("focus",function(){EjR(d,q,T)});
q.listen("blur",function(){j4R(d,q,T)});
q.listen("touchstart",function(){EjR(d,q,T)});
var J=g.bY("ytp-ce-expanding-overlay-hider",q.element);J&&q.W(J,"touchstart",function(F){F.stopPropagation();g.TR(q.element,"ytp-ce-element-hover");g.TR(q.element,"ytp-ce-force-expand")});
q.listen("keydown",function(F){d.lr=F.keyCode===9&&!F.shiftKey});
Y(g.bY("ytp-sb-subscribe",q.element));Y(g.bY("ytp-sb-unsubscribe",q.element));q.listen("focus",U);q.listen("blur",b)},aYQ=function(d,q,T){if(q.targetUrl&&(!T||T.type!=="keypress"||T.keyCode===13)){for(var Y=T.target;Y&&!g.V5(Y,"ytp-ce-element");){g.V5(Y,"subscribe-label")&&AAq(d,q);
if(g.V5(Y,"ytp-ce-channel-subscribe"))return;Y=Y.parentElement||null}if(!Y||g.V5(Y,"ytp-ce-element-hover")){T.preventDefault();T.stopPropagation();if(Y=d.U[q.id])j4R(d,Y,q),Y.element.blur();if(T.ctrlKey||T.metaKey||q.hfU==="new")AAq(d,q),d.player.sendVideoStatsEngageEvent(17,void 0),d.player.pauseVideo(),T=g.b4(w$(d,q.targetUrl)),T=g.YS(T),g.u2(T,void 0,q.sessionData);else{var e=g.cT(d.player.C())||d.player.getVideoData().kc,U=function(){var b=w$(d,q.targetUrl),J=q.sessionData,F=q.watchEndpoint,N=
g.oE(b);e&&N&&(N.v||N.list)?d.player.tC(N.v,J,N.list,!1,void 0,F||void 0):g.CG(b,J)};
AAq(d,q,function(){d.player.sendVideoStatsEngageEvent(17,U)})}}}},w$=function(d,q){d=d.player.C();
if(q){if(q.startsWith("//"))return d.protocol+":"+q;if(q.startsWith("/"))return g.nI(d)+q}else return"";return q},EjR=function(d,q,T){g.V5(q.element,"ytp-ce-element-hover")||(T.type==="VIDEO"||T.type==="PLAYLIST"?g.d9(q.element,"ytp-ce-element-hover"):d.player.C().U?(new g.f9(function(){g.d9(q.element,"ytp-ce-element-hover")},200)).start():g.d9(q.element,"ytp-ce-element-hover"),zw(d,T.jl),ff(d,T.id,!0))},j4R=function(d,q,T){g.TR(q.element,"ytp-ce-element-hover");
g.TR(q.element,"ytp-ce-force-expand");ff(d,T.id,!1)},ff=function(d,q,T){d.j&&(T?d.S.show():d.S.hide());
for(var Y=g.E(Object.keys(d.U)),e=Y.next();!e.done;e=Y.next())e=e.value,e!==q&&g.ep(d.U[e].element,"ytp-ce-element-shadow-show",T)},zw=function(d,q,T){function Y(){U||(e++,e===q.length&&(b.stop(),T&&T()))}
if(!q||q.length===0||Cf(d))T&&T();else{q=pEs(d,q);var e=0,U=!1,b=new g.f9(function(){U=!0;T&&T()},1E3,d);
b.start();for(d=0;d<q.length;d++)g.rM(q[d],Y)}},AAq=function(d,q,T){zw(d,q.clickUrls,T);
(d=g.Q0())&&q.aH&&g.dx(d,q.visualElement)},pEs=function(d,q){var T=d.player.getVideoData().clientPlaybackNonce;
d=d.player.getCurrentTime().toFixed(2);T={CPN:T,AD_CPN:T,MT:d};d=[];for(var Y=0;Y<q.length;Y++)d.push(Z$E(q[Y],T));return d},Z$E=function(d,q){return d.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(T){var Y=unescape(T);
Y=Y.substring(1,Y.length-1);return q[Y]?escape(q[Y]):T})},O$x=function(d){return typeof d==="string"?d:""},iJ=function(d,q,T){for(var Y in q)if(q[Y]===d)return d;
return T},njn=function(d,q,T,Y){this.value=d;
this.target=q;this.showLinkIcon=T;this.G=Y},IK=function(d){return d.value?d.value:null},mk=function(d){if(!d)return null;
var q=g.b4(O$x(d.value));q=g.YS(q);if(!q)return null;var T=iJ(d.target,rAl,"current");if(T==null)d=null;else{var Y=d.show_link_icon;d=new njn(q,T,Y==="true"||Y==="false"?Y==="true":!0,d.pause_on_navigation!=null?d.pause_on_navigation:!0)}return d},tEQ=function(d,q,T){this.type=d;
this.trigger=q;this.url=T},Gi7=function(d){if(!d)return null;
var q=iJ(d.type,BYx),T=iJ(d.trigger,KTx);d=d.url;d=Array.isArray(d)&&d.length?d[0]:d;d=mk(d?d:null);return q?new tEQ(q,T,d):null},LTl=function(d,q,T,Y,e){this.id=d;
this.type=q;this.style=T;this.data=e;this.action=Y||[]},kiI=function(d,q){return g.QN(d.action,q)},Pll=function(d,q){this.context=d;
this.G=q},WT_=function(d){return d.customMessage?SQ("div","iv-card-message",d.customMessage):""},lJ=function(d,q){d="background-image: url("+d+");";
var T=[];q&&T.push(q);return{Y:"div",D:"iv-card-image",Z:{style:d},V:T}},Cln=function(d){if(!d.metaInfo||d.metaInfo.length===0)return"";
var q=[];d=g.E(d.metaInfo);for(var T=d.next();!T.done;T=d.next())q.push(SQ("li","",T.value));return{Y:"ul",D:"iv-card-meta-info",V:q}},SQ=function(d,q,T){q?typeof q==="string"?q={"class":q}:Array.isArray(q)&&(q={"class":q.join(" ")}):q={};
q.dir=g.$G(T);return{Y:d,Z:q,j5:T}},ues=function(d){if(!d.customMessage)return"";
var q=["iv-card-action","iv-card-primary-link"],T={};d.J5&&(q.push("iv-card-action-icon"),T.style="background-image: url("+d.J5+");");T.dir=g.$G(d.customMessage);var Y=[{Y:"span",j5:d.customMessage}];d.showLinkIcon&&(Y.push("\u00a0"),Y.push({Y:"span",D:"iv-card-link-icon"}));return{Y:"div",hF:q,Z:T,V:Y}},vS=function(d,q,T,Y){if(Y){q=g.E(q);
for(var e=q.next();!e.done;e=q.next())d.G(e.value,Y,T.id,T.sessionData,T.tq.click,5)}},DbN=function(d,q){this.merchant=d;
this.price=q},wE7=function(d){var q;
(q=d)&&!(q=d.length>1?d.charAt(0)==="/"&&d.charAt(1)!=="/":d==="/")&&(q=d.replace(/^(https?:)?\/\//,"").split("/",1),q=!q||q.length<1||!q[0]?[]:q[0].toLowerCase().split(".").reverse(),q=q[0]==="com"&&q[1]==="youtube"||q[0]==="be"&&q[1]==="youtu");return q?d.indexOf("/redirect?")===-1:!1},fY_=function(d,q){return q?q:wE7(d)?"current":"new"},oK=function(d,q){g.W.call(this);
var T=this;this.element=d;this.context=q;this.kx=!1;this.xx=new Map;this.AF=new Map;this.context.J.addEventListener(g.Sh("annotations_module"),function(Y){(Y=T.xx.get(Y))&&Y.apply(T)});
this.context.J.addEventListener(g.lG("annotations_module"),function(Y){(Y=T.AF.get(Y))&&Y.apply(T)})},Vs=function(d,q,T,Y,e,U,b){d.context.G.listen(q,"click",function(J){d.CP(T,Y,e,U||[],b||0,J)});
d.context.G.listen(q,"touchstart",function(){d.kx=!1});
d.context.G.listen(q,"touchmove",function(){d.kx=!0})},z1B=function(d){var q;
return((q=g.D(d,g.KM))==null?0:q.url)?g.D(d,g.KM).url:(d=g.D(d,g.EB))&&d.videoId?(q="/watch?v="+d.videoId,d.playlistId&&(q+="&list="+d.playlistId),d.index&&(q+="&index="+d.index),d.startTimeSeconds&&(q+="&t="+d.startTimeSeconds),q):null},dy=function(d,q,T){return{iQ:(d.impressionLoggingUrlsV2s||[]).map(function(Y){return Y.baseUrl||""}),
click:(T.loggingUrls||[]).map(function(Y){return Y.baseUrl||""}),
close:(q.dismissLoggingUrlsV2s||[]).map(function(Y){return Y.baseUrl||""}),
I2:(q.impressionLoggingUrlsV2s||[]).map(function(Y){return Y.baseUrl||""}),
hw:(q.clickLoggingUrlsV2s||[]).map(function(Y){return Y.baseUrl||""})}},i$q=function(d,q,T){oK.call(this,q,T);
var Y=this;this.J=d;this.eventId=null;this.lF=this.aU=this.Qp=this.j=this.isInitialized=!1;this.cards=[];this.wO=this.S=this.dO=this.X=this.qk=this.G=null;this.lr=[];this.UD=this.B=this.BA=this.z2=null;this.L=0;this.rO=new g.f9(function(){},T.Pv.Gv?4E3:3E3);
g.C(this,this.rO);this.Bv=new g.f9(function(){});
g.C(this,this.Bv);this.yv=new Pll(T,function(e,U,b,J,F,N){Vs(Y,e,U,b,J,F,N)});
this.K=new g.f({Y:"div",D:"iv-drawer",Z:{id:"iv-drawer"},V:[{Y:"div",D:"iv-drawer-header",Z:{"aria-role":"heading"},V:[{Y:"span",D:"iv-drawer-header-text"},{Y:"button",hF:["iv-drawer-close-button","ytp-button"],Z:{"aria-label":"Hide cards",tabindex:"0"}}]},{Y:"div",D:"iv-drawer-content"}]});g.C(this,this.K);this.T=this.K.element;this.Fw=new g.oh(this.K,330);g.C(this,this.Fw);this.fn=g.bY("iv-drawer-header-text",this.T);this.U=g.bY("iv-drawer-content",this.T);this.addCueRange(0,T.videoData.lengthSeconds*
1E3,"",function(){Y.Qp&&q2(Y,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(Y.Qp=Y.j)&&T9(Y)});
this.RU=new g.aI(this);g.C(this,this.RU);this.J.addEventListener("videodatachange",this.qF.bind(this))},IYE=function(d,q){q=q.data;
q.autoOpenMs&&d.addCueRange(q.autoOpenMs,0x8000000000000,"",function(){q2(d,"YOUTUBE_DRAWER_AUTO_OPEN")});
q.autoCloseMs&&d.addCueRange(q.autoCloseMs,0x8000000000000,"",function(){T9(d)});
var T=q.headerText;g.Qp(d.fn,T);d.S&&(d.J.N("player_tooltip_data_title_killswitch")?d.S.setAttribute("title",T):d.S.setAttribute("data-tooltip-title",T));q.eventId&&(d.eventId=q.eventId);d.z2=g.y0(q.trackingParams);d.B=g.y0(q.closeTrackingParams);d.BA=g.y0(q.iconTrackingParams)},mb7=function(d,q){var T=q.cardId?q.cardId:"cr:"+d.L,Y=d.J.C().experiments.Wv("enable_error_corrections_infocard_web_client");
if(!q.content&&q.teaser.simpleCardTeaserRenderer&&Y){var e=q.teaser.simpleCardTeaserRenderer,U=q.icon?q.icon.infoCardIconRenderer:null;if(e.channelAvatar&&e.channelAvatar.thumbnails&&e.channelAvatar.thumbnails.length>0)var b=YF(e.channelAvatar.thumbnails,22,22).url;q={id:T,timestamp:d.L,type:"simple",teaserText:g.gx(e.message),teaserDurationMs:Number(q.cueRanges[0].teaserDurationMs),startMs:Number(q.cueRanges[0].startCardActiveMs),autoOpen:!!q.autoOpen,sessionData:{},sponsored:!1,tq:{},A8:null,Zc:e.trackingParams?
g.y0(e.trackingParams):null,BA:U&&U.trackingParams?g.y0(U.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,J5:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null,IG:b};em(d,q)}else{var J;if((J=q.content)==null?0:J.simpleCardContentRenderer){if(!q.cueRanges.length)return;b=(e=q.content)==null?void 0:e.simpleCardContentRenderer;e=q.teaser.simpleCardTeaserRenderer;U=q.icon?q.icon.infoCardIconRenderer:null;q={id:T,timestamp:d.L,type:"simple",teaserText:g.gx(e.message),
teaserDurationMs:Number(q.cueRanges[0].teaserDurationMs),startMs:Number(q.cueRanges[0].startCardActiveMs),autoOpen:!!q.autoOpen,sessionData:Uh(d,T,q,b),sponsored:!1,tq:dy(b,e,b.command),A8:b.trackingParams?g.y0(b.trackingParams):null,Zc:e.trackingParams?g.y0(e.trackingParams):null,BA:U&&U.trackingParams?g.y0(U.trackingParams):null,imageUrl:YF(b.image.thumbnails,290,290).url,displayDomain:b.displayDomain?g.gx(b.displayDomain):null,showLinkIcon:!!b.showLinkIcon,J5:null,title:b.title?g.gx(b.title):"",
customMessage:b.callToAction?g.gx(b.callToAction):"",url:g.D(b.command,g.KM).url?mk({pause_on_navigation:!d.context.videoData.isLivePlayback,target:"new",value:g.D(b.command,g.KM).url}):null,onClickCommand:null};em(d,q)}else{var F;if((F=q.content)==null?0:F.collaboratorInfoCardContentRenderer){if(!q.cueRanges.length)return;b=(U=q.content)==null?void 0:U.collaboratorInfoCardContentRenderer;e=q.teaser.simpleCardTeaserRenderer;U=q.icon?q.icon.infoCardIconRenderer:null;q={id:T,timestamp:d.L,type:"collaborator",
teaserText:g.gx(e.message),teaserDurationMs:Number(q.cueRanges[0].teaserDurationMs),startMs:Number(q.cueRanges[0].startCardActiveMs),autoOpen:!!q.autoOpen,sessionData:Uh(d,T,q,b),sponsored:!1,tq:dy(b,e,b.endpoint),A8:b.trackingParams?g.y0(b.trackingParams):null,Zc:e.trackingParams?g.y0(e.trackingParams):null,BA:U&&U.trackingParams?g.y0(U.trackingParams):null,channelId:g.D(b.endpoint,g.SH).browseId,customMessage:b.customText?g.gx(b.customText):null,profileImageUrl:YF(b.channelAvatar.thumbnails,290,
290).url,title:b.channelName?g.gx(b.channelName):"",metaInfo:[b.subscriberCountText?g.gx(b.subscriberCountText):""],url:mk({pause_on_navigation:!d.context.videoData.isLivePlayback,target:"new",value:g.D(b.endpoint,g.SH).canonicalBaseUrl?g.D(b.endpoint,g.SH).canonicalBaseUrl:"/channel/"+g.D(b.endpoint,g.SH).browseId}),onClickCommand:null};em(d,q)}else{var N;if((N=q.content)==null?0:N.playlistInfoCardContentRenderer){if(!q.cueRanges.length)return;var R;b=(R=q.content)==null?void 0:R.playlistInfoCardContentRenderer;
e=q.teaser.simpleCardTeaserRenderer;U=q.icon?q.icon.infoCardIconRenderer:null;q={id:T,timestamp:d.L,type:"playlist",teaserText:g.gx(e.message),teaserDurationMs:Number(q.cueRanges[0].teaserDurationMs),startMs:Number(q.cueRanges[0].startCardActiveMs),autoOpen:!!q.autoOpen,sessionData:Uh(d,T,q,b),sponsored:!1,tq:dy(b,e,b.action),A8:b.trackingParams?g.y0(b.trackingParams):null,Zc:e.trackingParams?g.y0(e.trackingParams):null,BA:U&&U.trackingParams?g.y0(U.trackingParams):null,hh:YF(b.playlistThumbnail.thumbnails,
258,290).url,customMessage:b.customMessage?g.gx(b.customMessage):null,playlistVideoCount:g.gx(b.playlistVideoCount),title:b.playlistTitle?g.gx(b.playlistTitle):"",metaInfo:[b.channelName?g.gx(b.channelName):"",b.videoCountText?g.gx(b.videoCountText):""],url:mk({pause_on_navigation:!d.context.videoData.isLivePlayback,target:"new",value:z1B(b.action)}),onClickCommand:null};em(d,q)}else{var x;if((x=q.content)==null?0:x.videoInfoCardContentRenderer){if(!q.cueRanges.length)return;var y;b=(y=q.content)==
null?void 0:y.videoInfoCardContentRenderer;e=q.teaser.simpleCardTeaserRenderer;U=q.icon?q.icon.infoCardIconRenderer:null;q={id:T,timestamp:d.L,type:"video",teaserText:g.gx(e.message),teaserDurationMs:Number(q.cueRanges[0].teaserDurationMs),startMs:Number(q.cueRanges[0].startCardActiveMs),autoOpen:!!q.autoOpen,sessionData:Uh(d,T,q,b),sponsored:!1,tq:dy(b,e,b.action),A8:b.trackingParams?g.y0(b.trackingParams):null,Zc:e.trackingParams?g.y0(e.trackingParams):null,BA:U&&U.trackingParams?g.y0(U.trackingParams):
null,hh:YF(b.videoThumbnail.thumbnails,258,290).url,videoDuration:b.lengthString?g.gx(b.lengthString):null,customMessage:b.customMessage?g.gx(b.customMessage):null,title:b.videoTitle?g.gx(b.videoTitle):"",metaInfo:[b.channelName?g.gx(b.channelName):"",b.viewCountText?g.gx(b.viewCountText):""],isLiveNow:!!b.badge,url:mk({pause_on_navigation:!d.context.videoData.isLivePlayback,target:"new",value:z1B(b.action)}),onClickCommand:null};em(d,q)}}}}}d.L++},YF=function(d,q,T){for(var Y=-1,e=-1,U=0;U<d.length;U++){if(d[U].height===
q||d[U].width===T)return d[U];
((d[U].height||0)<q||(d[U].width||0)<T)&&(Y<0||(d[Y].height||0)<(d[U].height||0)||(d[Y].width||0)<(d[U].width||0))?Y=U:((d[U].height||0)>=q||(d[U].width||0)>=T)&&(e<0||(d[e].height||0)>(d[U].height||0)||(d[e].width||0)>(d[U].width||0))&&(e=U)}return d[e>=0?e:Y]},Uh=function(d,q,T,Y){return{feature:T.feature?T.feature:"cards",
src_vid:d.context.videoData.videoId,annotation_id:q,ei:d.context.videoData.eventId||"",itct:Y.trackingParams||""}},lY_=function(d,q){if(q=SS_(d,q))q===d.G&&(d.G=null),d.J.removeCueRange(q.mj.id),g.h4(q.IJ),g.jj(d.cards,q),d.gR(),bX(d)},q2=function(d,q,T){if(!d.j){d.Fw.show();
d.qk=new g.f9(function(){g.d9(d.context.J.getRootNode(),g.Eo.IV_DRAWER_OPEN)},0);
d.qk.start();d.RU.W(d.U,"mousewheel",function(b){d.rO.start();b.preventDefault();b=b||window.event;var J=0;b.type=="MozMousePixelScroll"?J=0==(b.axis==b.HORIZONTAL_AXIS)?b.detail:0:window.opera?J=b.detail:J=b.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?b.wheelDeltaY/-30:b.wheelDeltaY/-1.2:b.wheelDelta/-1.6:b.wheelDeltaY/-3;if(b=J)d.U.scrollTop+=b});
d.j=!0;var Y=g.Q0();Y&&d.z2&&d.B&&g.o$(Y,[d.z2,d.B]);q={TRIGGER_TYPE:q};for(var e=g.E(d.cards),U=e.next();!U.done;U=e.next())U=U.value,U.j3||(U.j3=!0,vjI(d.context.logger,U.mj.tq.iQ,q)),Y&&g.o$(Y,[U.mj.A8]);r$(d.J);T&&(d.X=new g.f9(function(){d.dO=d.S;d.wO.focus()},330),d.X.start())}},T9=function(d){d.j&&(d.Fw.hide(),g.jX(d.RU),g.TR(d.context.J.getRootNode(),g.Eo.IV_DRAWER_OPEN),d.j=!1,r$(d.J),d.X&&d.X.stop(),d.X=new g.f9(function(){d.dO&&(d.dO.focus(),d.dO=null)},330),d.X.start())},ojI=function(d){g.qg(d.tA(),
[g.Eo.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.o6(d.J,d.T,5);d.R1();d.S=g.bY("ytp-cards-button",d.J.getRootNode());d.wO=g.bY("iv-drawer-close-button",d.T);d.isInitialized=!0},VEc=function(d){d.lr.push(g.ST("iv-teaser-shown",d.l2,d));
d.lr.push(g.ST("iv-teaser-hidden",d.Bc,d));d.lr.push(g.ST("iv-teaser-clicked",d.fF,d));d.lF=!0},dA_=function(d,q){var T;
return q.onClickCommand&&((T=g.D(q.onClickCommand,g.rnI))==null?void 0:T.targetId)==="engagement-panel-error-corrections"?(d.UD=q,!0):!1},qyN=function(d,q){d.UD=q;
var T=d.J.getVideoData();if(!T)return!1;T=g.Vv(T);if(T==null?0:T.markersMap)for(var Y,e=0;((Y=T)==null?void 0:Y.markersMap.length)>e;e++){var U=void 0,b=(U=T)==null?void 0:U.markersMap[e];if(b.key==="ERROR_CORRECTION_MARKERS"&&(U=void 0,(b=(U=b.value)==null?void 0:U.markers)&&b.length>0))return Y=void 0,q.startMs=((Y=g.D(b[0],g.YhH))==null?void 0:Y.timeRangeStartMillis)||0,d.UD=null,!0}return!1},em=function(d,q){if(!dA_(d,q)||qyN(d,q)){var T=T2L(d,q);
if(T){var Y={mj:q,IJ:T.element,j3:!1};if(q.onClickCommand)d.J.N("web_infocards_teaser_show_logging_fix")&&(d.lF||VEc(d),lY_(d,q.id),T=d.findLastIndex(Y),g.WR(d.cards,T,0,Y));else{d.isInitialized||ojI(d);lY_(d,q.id);var e=d.findLastIndex(Y);g.WR(d.cards,e,0,Y);T.IU(d.U,e);d.gR()}q.autoOpen?d.addCueRange(q.startMs,0x8000000000000,q.id,function(){d.j||(d.G=Y,bX(d),Yyx(d,Y),q2(d,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(T=d.context.J.getCurrentTime()*1E3,T<5E3&&T>q.startMs&&eZB(d,Y),d.addCueRange(q.startMs,
q.startMs+1,q.id,function(){eZB(d,Y)}),bX(d))}}},T2L=function(d,q){switch(q.type){case "simple":d=d.yv;
var T=q.displayDomain?{Y:"div",D:"iv-card-image-text",j5:q.displayDomain}:void 0;var Y=ues(q);T={Y:"div",hF:["iv-card"],V:[{Y:"a",D:"iv-click-target",Z:{href:q.url?IK(q.url)||"":""},V:[lJ(q.imageUrl,T),{Y:"div",D:"iv-card-content",V:[SQ("h2",void 0,q.title),Y]}]}]};T=new g.f(T);vS(d,g.eV("iv-click-target",T.element),q,q.url);q=T;break;case "collaborator":d=d.yv;T={Y:"div",hF:["iv-card","iv-card-channel"],V:[{Y:"a",hF:["iv-click-target"],Z:{href:IK(q.url)||"","data-ytid":q.channelId},V:[lJ(q.profileImageUrl),
{Y:"div",D:"iv-card-content",V:[WT_(q),{Y:"h2",D:"iv-card-primary-link",j5:q.title},Cln(q)]}]}]};T=new g.f(T);vS(d,g.eV("iv-click-target",T.element),q,q.url);q=T;break;case "playlist":d=d.yv;T={Y:"div",hF:["iv-card","iv-card-playlist"],V:[{Y:"a",D:"iv-click-target",Z:{href:IK(q.url)||""},V:[lJ(q.hh,{Y:"div",D:"iv-card-image-overlay",V:[{Y:"span",D:"iv-card-playlist-video-count",j5:q.playlistVideoCount}]}),{Y:"div",D:"iv-card-content",V:[WT_(q),SQ("h2","iv-card-primary-link",q.title),Cln(q)]}]}]};
T=new g.f(T);vS(d,g.eV("iv-click-target",T.element),q,q.url);q=T;break;case "productListing":d=d.yv;var e=q.offers.length!=0;T=["iv-card"];Y="";var U=ues(q);e&&(T.push("iv-card-product-listing"),Y="iv-card-primary-link",U=q.offers[0],e=[],U.price&&e.push({Y:"div",D:"iv-card-offer-price",j5:U.price}),U.merchant&&e.push({Y:"div",D:"iv-card-offer-merchant",j5:U.merchant}),U={Y:"div",V:e});e=q.url?IK(q.url)||"":"";T={Y:"div",hF:T,Z:{tabindex:"0"},V:[{Y:"a",hF:["iv-card-image","iv-click-target"],Z:{style:"background-image: url("+
q.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{Y:"div",D:"iv-card-content",V:[q.sponsored?{Y:"div",D:"iv-card-sponsored",V:["Sponsored",{Y:"div",D:"iv-ad-info-container",V:[{Y:"div",D:"iv-ad-info",j5:"{{adInfo}}"},{Y:"div",D:"iv-ad-info-icon-container",V:[{Y:"div",D:"iv-ad-info-icon"},{Y:"div",D:"iv-ad-info-callout"}]}]}]}:"",{Y:"a",D:"iv-click-target",Z:{href:e},V:[SQ("h2",Y,q.title),U]}]}]};T=new g.f(T);Y=g.FE("span");g.Qp(Y,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
T.A1(Y,"adInfo");vS(d,g.eV("iv-click-target",T.element),q,q.url);q=T;break;case "video":d=d.yv;Y=q.videoDuration?{Y:"span",D:"iv-card-video-duration",j5:q.videoDuration}:void 0;U=q.isLiveNow?{Y:"span",hF:["yt-badge","yt-badge-live"],j5:"LIVE NOW"}:null;e={Y:"div",hF:["iv-card","iv-card-video"],V:[{Y:"a",D:"iv-click-target",Z:{href:((T=q.url)==null?void 0:IK(T))||""},V:[lJ(q.hh,Y),{Y:"div",D:"iv-card-content",V:[WT_(q),SQ("h2","iv-card-primary-link",q.title),Cln(q),U]}]}]};T=new g.f(e);vS(d,g.eV("iv-click-target",
T.element),q,q.url);q=T;break;default:return null}return q},UA_=function(d){if(d.G)return d.G.mj.type==="productListing";
if(d.J.N("enable_wn_infocards")){var q;return!((q=d.cards)==null||!q.length)&&g.h0(d.cards,function(T){return T.mj.type==="productListing"})}return g.h0(d.cards,function(T){return T.mj.type==="productListing"})},bX=function(d){g.ep(d.J.getRootNode(),"ytp-cards-shopping-active",UA_(d))},eZB=function(d,q){if(!g.V5(d.J.getRootNode(),"ytp-cards-teaser-shown")){if(d.G!==q){var T=g.Q0(),Y=d.G?d.G.mj.BA:d.BA;
T&&Y&&g.V0(T,[Y]);d.G=q;bX(d)}(T=d.isInitialized&&d.tA().style.display=="none")||(T=d.context.J.getPlayerState(),Y=T===0&&d.context.J.getCurrentTime()===0,T=!(T===1||T===3||Y));if(!T&&q.mj.teaserDurationMs){var e;T={teaserText:q.mj.teaserText,durationMs:q.mj.teaserDurationMs,onClickCommand:q.mj.onClickCommand,IG:(e=q.mj.IG)!=null?e:null};d.J.sJ(!0,T)}d.Bv.isActive()||((!d.j||!d.rO.isActive()&&d.aU)&&Yyx(d,q),d.Bv.start(910+q.mj.teaserDurationMs))}},Yyx=function(d,q){d.K.PF?(q=new Lf([0,
d.U.scrollTop],[0,q.IJ.offsetTop],600,gjn),d.context.j.listen(q,"animate",function(T){d.U.scrollTop=T.y}),d.context.j.listen(q,"finish",function(T){d.U.scrollTop=T.y}),q.play()):(d.K.OM(!0),d.U.scrollTop=q.IJ.offsetTop,d.K.OM(!1))},XB=function(d){return d.G&&d.G.mj?d.G.mj:d.cards[0]&&d.cards[0].mj?d.cards[0].mj:null},SS_=function(d,q){return g.QN(d.cards,function(T){return T.mj.id===q})},J2=function(d,q,T){oK.call(this,d,q);
this.annotation=T;this.isActive=!1},b2E=function(d){var q=d.annotation.data;
"start_ms"in q&&"end_ms"in q&&d.addCueRange(Number(q.start_ms),Number(q.end_ms),d.annotation.id,function(){d.show()},function(){d.hide()})},sh=function(d,q,T){J2.call(this,d,q,T);
this.U=null;this.L=!1;this.j=null;this.T=!1;this.G=this.X=this.S=null},XVn=function(d,q){var T=T===void 0?0:T;
var Y=TYE(q).width;g.mZ(q,Y);T=new s4B(q,[Y,q.offsetTop],[Y-Y-T,q.offsetTop],200,$bR);g.C(d,T);d.context.j.listen(T,"begin",function(){g.dv(q,!0)});
T.play()},$AB=function(d,q){if(q.channel_name){var T=d.createElement({Y:"div",
hF:["iv-branding-context-name"],j5:q.channel_name}),Y=d.createElement({Y:"div",hF:["iv-branding-context-subscribe"]}),e=q.standalone_subscribe_button_data;e&&(d.G=new g.Jg(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,q.channel_id,!!e.subscribed,e.feature,q.session_data.itct,d.context.J,!1),d.G.IU(Y));var U=d.createElement({Y:"div",hF:["iv-branding-context-subscribe-caret"]}),b=d.createElement({Y:"div",hF:["branding-context-container-inner"]});b.appendChild(U);
b.appendChild(T);b.appendChild(Y);g.dv(b,!1);var J=d.createElement({Y:"div",hF:["branding-context-container-outer"]});J.appendChild(b);g.Dv(J,"right",q.image_width+"px");g.Rr(d.tA(),J);d.j=new g.f9(function(){JIl(d,b,J)},500);
g.C(d,d.j);d.context.G.listen(d.tA(),"mouseover",function(){slc(d,b,J,U,q.image_height)});
d.context.G.listen(d.tA(),"mouseout",function(){d.j.start()})}},slc=function(d,q,T,Y,e){d.j.stop();
if(!d.T){var U=g.Vp(q);d.G||(q.style.width=g.Ir(U.width,!0),T.style.width=g.Ir(U.width,!0));g.Dv(Y,"top",U.height-Math.max(Math.min(U.height,e)/2+10,20)+"px");g.Dv(Y,"right","1px");d.T=!0;g.dv(q,!0);d.S=new g.f9(function(){g.d9(this.tA(),"iv-branding-active")},0,d);
d.S.start()}},JIl=function(d,q,T){g.TR(d.tA(),"iv-branding-active");
d.X=new g.f9(function(){g.dv(q,!1);d.G||(T.style.width=g.Ir(0,!0))},250);
d.X.start();d.T=!1},gJn=function(d,q,T,Y,e,U,b){this.G=d;
this.j=q;this.Pv=T;this.videoData=Y;this.logger=e;this.J=U;this.U=b},Fgl=function(d,q,T){J2.call(this,d,q,T);
var Y=this;this.B=this.isCollapsed=this.K=!1;this.X=5E3;this.U=this.j=this.G=this.T=null;this.L=this.createElement({Y:"div",hF:["iv-promo-contents"]});this.S=new g.f9(function(){Y.G.setAttribute("aria-hidden","true");g.dv(Y.j,!1);g.dv(Y.U,!0)},700,this);
g.C(this,this.S)},RZ_=function(d){var q=d.annotation.data;
if(d.annotation.style==="cta")var T=6;else if(d.annotation.style==="video"||d.annotation.style==="playlist")T=7;d.X=q.collapsedelay_ms||d.X;var Y=["iv-promo","iv-promo-inactive"];d.tA().setAttribute("aria-hidden","true");d.tA().setAttribute("aria-label","Promotion");d.tA().tabIndex=0;var e=d.annotation.Hl(),U=q.image_url;if(U){var b=d.createElement({Y:"div",hF:["iv-promo-img","iv-click-target"]});U=d.createElement({Y:"img",Z:{src:U,"aria-hidden":"true"}});b.appendChild(U);q.video_duration&&!q.is_live?
(U=d.createElement({Y:"span",D:"iv-promo-video-duration",j5:q.video_duration}),b.appendChild(U)):q.playlist_length&&(U=d.createElement({Y:"span",D:"iv-promo-playlist-length",j5:q.playlist_length.toString()}),b.appendChild(U));e&&Vs(d,b,e,d.annotation.id,q.session_data,void 0,T)}e?(U=d.createElement({Y:"a",D:"iv-promo-txt"}),g.sD(U,IK(e)),d.G=U):d.G=d.createElement({Y:"div",D:"iv-promo-txt"});switch(d.annotation.style){case "cta":case "website":var J=d.createElement({Y:"p",V:[{Y:"strong",j5:q.text_line_1}]});
var F=d.createElement({Y:"p",V:[{Y:"span",D:"iv-promo-link",j5:q.text_line_2}]});if(U=q.text_line_3){Y.push("iv-promo-website-card-cta-redesign");var N=d.createElement({Y:"button",hF:["iv-promo-round-expand-icon","ytp-button"]});U=d.createElement({Y:"button",hF:["iv-button","iv-promo-button"],V:[{Y:"span",D:"iv-button-content",j5:U}]});var R=d.createElement({Y:"div",D:"iv-promo-button-container"});R.appendChild(U);e&&Vs(d,d.tA(),e,d.annotation.id,q.session_data,void 0,T)}g.d9(d.G,"iv-click-target");
e&&Vs(d,d.G,e,d.annotation.id,q.session_data,void 0,T);break;case "playlist":case "video":J=d.createElement({Y:"p",V:[{Y:"span",j5:q.text_line_1}]}),F=d.createElement({Y:"p",V:[{Y:"strong",j5:q.text_line_2}]}),q.is_live&&(J=F,F=d.createElement({Y:"span",hF:["yt-badge","iv-promo-badge-live"],j5:"LIVE NOW"})),g.d9(d.G,"iv-click-target"),e&&Vs(d,d.G,e,d.annotation.id,q.session_data,void 0,T),Y.push("iv-promo-video")}J&&d.G.appendChild(J);F&&d.G.appendChild(F);d.L.appendChild(d.G);R&&d.L.appendChild(R);
T=d.createElement({Y:"div",D:"iv-promo-actions"});d.U=d.createElement({Y:"button",hF:["iv-promo-expand","ytp-button"]});d.U.title="Expand";d.context.G.listen(d.U,"click",function(x){N2q(d,5E3,x)});
T.appendChild(d.U);g.dv(d.U,!1);d.context.G.listen(d.tA(),"mouseover",d.NE,d);d.context.G.listen(d.tA(),"mouseout",d.nI,d);d.context.G.listen(d.tA(),"touchend",function(x){N2q(d,5E3,x)});
d.j=d.createElement({Y:"button",hF:["iv-promo-close","ytp-button"]});d.j.title="Close";d.context.G.listen(d.j,"click",d.annotation.style==="cta"&&q.text_line_3?d.mC:d.qE,d);T.appendChild(d.j);g.qg(d.tA(),Y);b&&(g.Rr(d.tA(),b),N&&b.appendChild(N));g.Rr(d.tA(),d.L);g.Rr(d.tA(),T)},N2q=function(d,q,T){T.stopPropagation();
xAE(d);yIL(d,q);d.G.focus()},hZL=function(d){d.isCollapsed||d.B||d.T||(g.d9(d.tA(),"iv-promo-collapsed"),d.isCollapsed=!0,d.S.start())},xAE=function(d){d.S.stop();
d.isCollapsed&&(g.YG(d.tA(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),d.isCollapsed=!1,d.G&&d.G.removeAttribute("aria-hidden"),g.dv(d.U,!1),g.dv(d.j,!0))},yIL=function(d,q){d.T||(d.T=g.GB(function(){H2L(this);
hZL(this)},q,d))},H2L=function(d){d.T&&(g.oQ.clearTimeout(d.T),d.T=null)},QlI=function(d){this.J=d},vjI=function(d,q,T){q&&(T?$F(d,q.map(function(Y){return g.a1(Y,T)})):$F(d,q))},$F=function(d,q,T,Y){var e=1,U=void 0,b=-1;
if(T){var J=!1;U=function(){e--;e||J||(clearTimeout(b),J=!0,T())};
b=setTimeout(function(){J=!0;T()},1E3)}q=g.E(q||[]);
for(var F=q.next();!F.done;F=q.next())F=F.value,e++,g.rM(F,U);Y&&(e++,Y!==0&&d.J.sendVideoStatsEngageEvent(Y,U))},Mss=function(d){g.na.call(this,d);
var q=this;this.lr=this.B=!1;this.loadNumber=0;this.X={};this.logger=new QlI(this.player);this.T=new g.aI(this);this.S=this.L=null;this.events=new g.aI(this);this.x9=this.K=this.G=null;this.UD=[];g.C(this,this.T);this.T.W(this.player,"onVideoAreaChange",function(){q.publish("onVideoAreaChange")});
this.T.W(this.player,"onHideControls",function(){q.publish("onHideControls")});
this.T.W(this.player,"onShowControls",function(){q.publish("onShowControls")});
this.T.W(this.player,"resize",function(Y){q.publish("resize",Y)});
this.T.W(this.player,"presentingplayerstatechange",function(Y){q.publish("presentingplayerstatechange",Y)});
this.subscribe("presentingplayerstatechange",this.Ut,this);this.subscribe("resize",this.gF,this);this.player.C().aU.subscribe("vast_info_card_add",this.JK,this);g.C(this,this.events);this.yv=this.createElement({Y:"div",D:"video-custom-annotations"});this.U=new g.f({Y:"div",hF:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.U);g.o6(this.player,this.U.element,4);this.U.hide();this.j=new g.f({Y:"div",hF:["ytp-iv-video-content"]});g.C(this,this.j);d=this.createElement({Y:"div",D:"video-annotations"});
d.appendChild(this.yv);this.j.element.appendChild(d);this.GB()&&this.load();var T=this.createElement({Y:"style"});(g.YE("HEAD")[0]||document.body).appendChild(T);this.addOnDisposeCallback(function(){g.h4(T)});
if(d=T.sheet)d.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),d.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),d.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),d.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),d.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),d.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),d.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),d.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),d.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),d.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},cIN=function(d){d=d.createElement({Y:"div",
hF:["annotation","annotation-type-custom"]});g.dv(d,!1);return d},EJ7=function(d,q){q=!q.isCued()&&!g.I(q,1024);
d.U.OM(q);d.j.OM(q)},jlB=function(d,q,T){d.B=!0;
d.S=g.QB(q,T)},acs=function(d,q){for(var T={},Y=g.E(q.attributes),e=Y.next();!e.done;e=Y.next())e=e.value,T[e.name]=e.nodeValue;
for(Y=0;Y<q.childNodes.length;Y++)if(e=q.childNodes[Y],g.UI(e)&&e.nodeType==1){if(T[e.tagName])var U=T[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(U=e.childNodes[0].nodeValue,T[e.tagName]=typeof U==="string"?U.trim():U);continue}else U=[],T[e.tagName]=U;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?U.push(e.childNodes[0].nodeValue):U.push(""):e&&U.push(acs(d,e))}return T},O2B=function(d){var q=d.player.getVideoData();
if(q.RU){var T=d.player.C().aU.get(q.videoId);if(T){var Y={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,U,b){e=d.loadNumber;U=q.videoId;d.loaded&&d.loadNumber===e&&d.player.getVideoData().videoId===U&&(b=g.Jd(b)&&b.responseXML?b.responseXML:null)&&AI7(d,b)}};
g.m2()&&(Y.onFinish=pV7(d,Y.onFinish));Y.postParams={ic_only:"1"};Z2I(Y,T);d.B=!0;g.QB(q.RU,Y)}}},Z2I=function(d,q){d.method="POST";
d.postParams=d.postParams||{};q.cQ&&(d.postParams.ic_coll=q.cQ);q.YR&&(d.postParams.ic_xml=q.YR);q.NB&&(d.postParams.ic_track=q.NB)},nJE=function(d){var q=new g.f({Y:"div"});
g.dv(q.element,!1);var T=new i$q(d.player,q.element,gy(d));g.C(T,q);q.IU(d.U.element);T.Py();return T},ts7=function(d,q){var T,Y;
if(q=(T=q.getWatchNextResponse())==null?void 0:(Y=T.cards)==null?void 0:Y.cardCollectionRenderer)d.lr=!0,rIn(d,q),q.headerText&&d.x9&&(T=g.gx(q.headerText),d.player.N("player_tooltip_data_title_killswitch")?d.x9.setAttribute("title",T):d.x9.setAttribute("data-tooltip-title",T))},gy=function(d){if(!d.K){var q=new FTB(d);
g.C(d,q);var T=new g.FO(d);g.C(d,T);d.K=new gJn(q,T,d.player.C(),d.player.getVideoData(),d.logger,d.player,d.Y1)}return d.K},AI7=function(d,q){var T=!1,Y=q.getElementsByTagName("annotations");
if(Y&&!(Y.length<1)&&(Y=Y[0].getAttribute("itct"))){var e=g.Q0();if(e){var U=g.Ha();U&&g.iF(g.C1)(void 0,e,U,[g.y0(Y)])}}q=q.getElementsByTagName("annotation");for(Y=0;Y<q.length;Y++){U=acs(d,q[Y]);e=null;try{if(U){var b=U.id,J=/.+/;var F=typeof b==="string"&&J!=null&&b!=null&&b.match(J)?b:"";var N=iJ(U.type,B2N),R=iJ(U.style,KgQ),x=O$x(U.data),y=x.length!==0?JSON.parse(x):{};var h=U.action;U=Gi7;if(h==null)var H=null;else if(g.ej(h)){J=[];for(var a=g.E(h),p=a.next();!p.done;p=a.next()){var t=U(p.value);
t&&J.push(t)}H=J}else{var n=U(h);H=n?[n]:[]}e=F&&N?new LTl(F,N,R,H,y):null}else e=null}catch(b_){}if(e)if(e.type==="branding"||e.type==="promotion"){U=d;J=e;var K=cIN(U),P=null;switch(J.type){case "branding":if(U.player.C().gk)break;U.player.N("web_player_overlay_positioned_layout")?(K.setAttribute("data-overlay-order","11"),U.player.A0(K,4,!0)):U.U.element.appendChild(K);P=new sh(K,gy(U),J);break;case "promotion":g.o6(U.player,K,4),P=new Fgl(K,gy(U),J)}P&&P.Py();if(U=P)g.C(d,U),d.X[e.id]=U}else if(e.type===
"card"||e.type==="drawer"){d.G||(d.G=nJE(d),g.C(d,d.G));if(e.type==="card"){K=d.G;var w=(T=e)&&T.data&&T.data.card_type;e=T.data;if(w)switch(U=e.tracking||{},U={iQ:U.impression,click:U.click,close:U.close,I2:U.teaser_impression,hw:U.teaser_click},J=e.tracking_params||{},P=null,w){case "collaborator":T={id:T.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||
!1,tq:U,A8:J.card?g.y0(J.card):null,Zc:J.teaser?g.y0(J.teaser):null,BA:J.icon?g.y0(J.icon):null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:mk({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};em(K,T);break;case "playlist":T={id:T.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,
autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,tq:U,A8:J.card?g.y0(J.card):null,Zc:J.teaser?g.y0(J.teaser):null,BA:J.icon?g.y0(J.icon):null,hh:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:mk({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};em(K,T);break;case "productListing":e.signin_url&&(P=mk({target:"current",
value:e.signin_url}));w=[];for(var l=e.offers||[],m=0;m<l.length;m++)w.push(new DbN(g.rt(l[m].merchant),g.rt(l[m].price)));T={id:T.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,tq:U,A8:J.card?g.y0(J.card):null,Zc:J.teaser?g.y0(J.teaser):null,BA:J.icon?g.y0(J.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:
null,showLinkIcon:!!e.show_link_icon,J5:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:mk({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),T9D:P,ilF:e.signin_title?e.signin_title:void 0,j9U:e.signin_message?e.signin_message:void 0,offers:w,onClickCommand:null};em(K,T);break;case "simple":T={id:T.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,tq:U,A8:J.card?g.y0(J.card):null,Zc:J.teaser?g.y0(J.teaser):null,BA:J.icon?g.y0(J.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,J5:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:mk({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};
em(K,T);break;case "video":T={id:T.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,tq:U,A8:J.card?g.y0(J.card):null,Zc:J.teaser?g.y0(J.teaser):null,BA:J.icon?g.y0(J.icon):null,hh:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,
url:mk({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},em(K,T)}}else IYE(d.G,e);T=!0}}T&&(r$(d.player),d.gF())},rIn=function(d,q){var T=!1;
d.G||(d.G=nJE(d),g.C(d,d.G));for(var Y=g.E(q.cards||[]),e=Y.next();!e.done;e=Y.next())e=e.value,e.cardRenderer&&(mb7(d.G,e.cardRenderer),T=!0);if(T){var U;(U=d.player.getVideoData())!=null&&g.TJ(U)||(T=d.G,Y=q.headerText?g.gx(q.headerText):"",g.Qp(T.fn,Y),T.S&&(T.J.N("player_tooltip_data_title_killswitch")?T.S.setAttribute("title",Y):T.S.setAttribute("data-tooltip-title",Y)),T.context.videoData.eventId&&(T.eventId=T.context.videoData.eventId),T.z2=q.trackingParams?g.y0(q.trackingParams):null,T.B=
q.closeButton.infoCardIconRenderer.trackingParams?g.y0(q.closeButton.infoCardIconRenderer.trackingParams):null,T.BA=q.icon.infoCardIconRenderer.trackingParams?g.y0(q.icon.infoCardIconRenderer.trackingParams):null,d.gF());r$(d.player)}},Gg7=function(d,q,T,Y,e){if(!d.player.C().gk){var U=[];
q.navigationEndpoint&&g.D(q.navigationEndpoint,g.SH)&&g.D(q.navigationEndpoint,g.SH).browseId&&U.push(new tEQ("openUrl","click",new njn("/channel/"+g.D(q.navigationEndpoint,g.SH).browseId,"new",!0,!0)));var b=q.watermark.thumbnails[0];Y={channel_name:q.channelName,end_ms:q.endTimeMs,image_height:b.height,image_type:1,image_url:b.url,image_width:b.width,is_mobile:!1,session_data:{annotation_id:T,ei:e,feature:"iv",itct:q.trackingParams,src_vid:Y},start_ms:q.startTimeMs};if(q.subscribeButton&&g.D(q.subscribeButton,
g.lx)){Y.channel_id=g.D(q.subscribeButton,g.lx).channelId;var J;q=g.D(q.subscribeButton,g.lx);b=e=null;q.subscribed?(q.subscriberCountWithUnsubscribeText&&(e=g.gx(q.subscriberCountWithUnsubscribeText)),q.subscriberCountText&&(b=g.gx(q.subscriberCountText))):(q.subscriberCountText&&(e=g.gx(q.subscriberCountText)),q.subscriberCountWithSubscribeText&&(b=g.gx(q.subscriberCountWithSubscribeText)));var F,N=((F=g.D((J=q.signInEndpoint)==null?void 0:J.commandMetadata,g.AX))==null?void 0:F.url)||"";J={subscribeText:g.gx(q.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.gx(q.subscribedButtonText),unsubscribeCount:b||"",enabled:q.enabled||!1,classic:!1,subscribed:q.subscribed||!1,feature:"iv",signInUrl:N};Y.standalone_subscribe_button_data=J}U=new LTl(T,"branding","branding",U,Y);J=cIN(d);d.player.N("web_player_overlay_positioned_layout")?(J.setAttribute("data-overlay-order","11"),d.player.A0(J,4,!0)):d.U.element.appendChild(J);U=new sh(J,gy(d),U);U.Py();g.C(U,U);d.X[T]=U}},pV7=function(d,q){return function(){var T=g.CN.apply(0,
arguments);
d.JF()||d.UD.push(g.Gh.DE(function(){q.apply(null,g.RQ(T))}))}},LgI=function(d){return d==="annotation-editor"||d==="live-dashboard"};
g.fV.prototype.sJ=g.eD(39,function(d,q){var T=g.Df(this.M5());T&&T.sJ(d,q)});
var BS={},Kf=null;g.Rs(Lf,g.UA);g.Q=Lf.prototype;g.Q.getDuration=function(){return this.duration};
g.Q.play=function(d){if(d||this.G==0)this.progress=0,this.coords=this.U;else if(this.isPlaying())return!1;Gw(this);this.startTime=d=g.F_();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.T=this.startTime;this.progress||this.Ry();this.Ex("play");this.isPaused()&&this.Ex("resume");this.G=1;var q=g.X_(this);q in BS||(BS[q]=this);Ubq();b$s(this,d);return!0};
g.Q.stop=function(d){Gw(this);this.G=0;d&&(this.progress=1);XEl(this,this.progress);this.onStop();this.YG()};
g.Q.pause=function(){this.isPlaying()&&(Gw(this),this.G=-1,this.Ex("pause"))};
g.Q.ir=function(){this.G==0||this.stop(!1);this.Ex("destroy");Lf.VX.ir.call(this)};
g.Q.destroy=function(){this.dispose()};
g.Q.OT=function(){this.Ex("animate")};
g.Q.Ex=function(d){this.dispatchEvent(new JAI(d,this))};
g.Rs(JAI,g.fb);g.Rs(kd,Lf);kd.prototype.j=function(){};
kd.prototype.OT=function(){this.j();kd.VX.OT.call(this)};
kd.prototype.YG=function(){this.j();kd.VX.YG.call(this)};
kd.prototype.Ry=function(){this.j();kd.VX.Ry.call(this)};
g.Rs(s4B,kd);s4B.prototype.j=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.M(FTB,g.W);g.Q=FTB.prototype;g.Q.listen=function(d,q,T,Y){T=(0,g.sI)(T,Y||this.U);d=g.yi(d,q,T);this.G.push(d);return d};
g.Q.zg=function(d,q,T,Y){T=(0,g.sI)(T,Y||this.U);d=YSl(d,q,T);this.G.push(d);return d};
g.Q.t1=function(d){g.hB(d);g.jj(this.G,d)};
g.Q.removeAll=function(){g.hB(this.G);this.G.length=0};
g.Q.ir=function(){this.removeAll();g.W.prototype.ir.call(this)};g.M(xbN,g.na);g.Q=xbN.prototype;g.Q.load=function(){g.na.prototype.load.call(this);if(!Cf(this)){var d=g.S7f(this.player.getVideoData());d?(d=R1R(d,yAn(this)),uJ(this,d,!1)):h1Q(this)}};
g.Q.unload=function(){uJ(this,null);this.T&&(this.T.abort(),this.T=null);g.na.prototype.unload.call(this)};
g.Q.Vg=function(d,q){return Cf(this)?d==="loadCustomEndscreenRenderer"?(d=R1R(q,"new"),uJ(this,d),!0):null:null};
g.Q.getOptions=function(){return Cf(this)?["loadCustomEndscreenRenderer"]:[]};
g.Q.gz=function(){if(this.endscreen&&this.endscreen.elements){var d=this.player.getVideoContentRect();if(d&&d.width!==0&&d.height!==0){var q=this.player.getPlayerSize();if(q&&q.width!==0&&q.height!==0){var T=d.width/d.height;var Y=0;for(var e=-1,U=0;U<kgl.length;U++){var b=Math.abs(q.width-kgl[U]);if(e===-1||Y>=b)e=U,Y=b}Y=PDx[e];this.j&&g.Dv(this.j.element,"outline-width",Math.max(q.width,q.height)+"px");for(q=0;q<this.endscreen.elements.length;++q)if(U=this.endscreen.elements[q].id,e=this.U[U],
b=this.X[U],e&&b){var J=b.width*T/b.aspectRatio,F=Math.round(b.width*d.width);U=Math.round(J*d.height);var N=d.left+Math.round(b.left*d.width),R=d.top+Math.round(b.top*d.height);g.or(e.element,F,U);g.mZ(e.element,N,R);g.YG(e.element,Wgc);F>256||U>256?g.d9(e.element,"ytp-ce-large-round"):F>96||U>96?g.d9(e.element,"ytp-ce-medium-round"):g.d9(e.element,"ytp-ce-small-round");g.YG(e.element,CDL);F=b.left+b.width/2;b=b.top+J/2;g.d9(e.element,F<=.5&&b<=.5?"ytp-ce-top-left-quad":F>.5&&b<=.5?"ytp-ce-top-right-quad":
F<=.5&&b>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.YG(e.element,PDx);g.d9(e.element,Y);(e=g.UM(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Dv(e,"height",U+"px")}}}}};
g.Q.onCueRangeEnter=function(d){if(this.endscreen)if(d.getId()==="ytp-ce-in-endscreen")zw(this,this.endscreen.impressionUrls),(d=g.Q0())&&this.endscreen.visualElement&&g.va(d,this.endscreen.visualElement),this.G&&(g.d9(this.G,"ytp-ce-element-show"),this.G.removeAttribute("aria-hidden"),this.player.Tv()?g.d9(this.G,"ytp-ce-hide-button-lower"):g.TR(this.G,"ytp-ce-hide-button-lower"));else{d=d.getId().substring(15);var q=this.U[d],T=this.X[d];g.d9(q.element,"ytp-ce-element-show");q.element.removeAttribute("aria-hidden");
q=this.player.getRootNode();g.d9(q,"ytp-ce-shown");zw(this,T.impressionUrls);(q=g.Q0())&&g.va(q,T.visualElement);this.player.C().B&&this.player.gO("endscreenelementshown",d)}};
g.Q.onCueRangeExit=function(d){if(d.getId()==="ytp-ce-in-endscreen")this.G&&(g.TR(this.G,"ytp-ce-element-show"),this.G.setAttribute("aria-hidden","true"));else{d=d.getId().substring(15);var q=this.U[d];g.TR(q.element,"ytp-ce-element-show");q.element.setAttribute("aria-hidden","true");q=this.player.getRootNode();g.TR(q,"ytp-ce-shown");this.player.C().B&&this.player.gO("endscreenelementhidden",d)}};
g.Q.hUk=function(d){var q=this;d.target===window&&(new g.f9(function(){for(var T=g.E(Object.values(q.U)),Y=T.next();!Y.done;Y=T.next())g.YG(Y.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.Q.OM=function(d){for(var q=g.E(Object.values(this.U)),T=q.next();!T.done;T=q.next())T=T.value,d?T.element.setAttribute("hidden",""):T.element.removeAttribute("hidden")};
g.Q.xUv=function(d){this.G&&this.player.getRootNode().removeChild(this.G);d&&(g.d9(d,"ytp-ce-hide-button-container"),this.G=d,g.o6(this.player,this.G,4))};
var kgl=[346,426,470,506,570,640,853,1280,1920],PDx="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),CDL=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Wgc=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var rAl={Gzw:"current",EzF:"new"};var BYx={CLOSE:"close",xFr:"openUrl",SUBSCRIBE:"subscribe"},KTx={NHU:"click",CLOSE:"close",lpx:"hidden",XKx:"rollOut",qgD:"rollOver",glw:"shown"};LTl.prototype.Hl=function(){var d=kiI(this,function(q){return q.type==="openUrl"&&q.url!=null});
return d?d.url:null};
var KgQ={gLv:"anchored",No:"branding",CHANNEL:"channel",P1r:"cta",jQ2:"highlightText",ZqZ:"label",PLAYLIST:"playlist",POPUP:"popup",VHr:"speech",SUBSCRIBE:"subscribe",yCw:"title",VIDEO:"video",ZS2:"website"},B2N={No:"branding",dNw:"card",zLv:"drawer",oZw:"highlight",Qfw:"marker",TrD:"promotion",TEXT:"text",HoZ:"widget"};g.M(oK,g.W);g.Q=oK.prototype;g.Q.addCueRange=function(d,q,T,Y,e){d=new g.Ij(d,q,{id:T,namespace:"annotations_module"});Y&&this.xx.set(d,Y);e&&this.AF.set(d,e);this.context.J.ES([d],1)};
g.Q.Py=function(){this.context.U.subscribe("resize",this.gR,this)};
g.Q.tA=function(){return this.element};
g.Q.CP=function(d,q,T,Y,e,U){if(this.kx)return!1;U&&(U.stopPropagation(),U.preventDefault());this.navigate(d,T,Y,e);return!1};
g.Q.show=function(){};
g.Q.hide=function(){};
g.Q.destroy=function(){g.h4(this.tA())};
g.Q.gR=function(){};
g.Q.navigate=function(d,q,T,Y){var e=this,U=IK(d);if(U){var b=fY_(U,d.target),J=function(){d.G&&e.context.J.pauseVideo();var F=e.context.videoData.kc||!1,N=g.oE(U||"");F&&N&&(N.v||N.list)?e.context.J.tC(N.v,q,N.list,!1):g.u2(U||"",b==="current"?"_top":void 0,q)};
b==="new"&&(J(),J=null);$F(this.context.logger,T,J,Y);wE7(U)||(T=g.Q0(),Y=q.itct,T&&Y&&g.dx(T,g.y0(Y)))}};
g.Q.ir=function(){this.xx.clear();this.AF.clear();g.W.prototype.ir.call(this)};
g.Q.createElement=function(d){d=new g.f(d);g.C(this,d);return d.element};g.M(i$q,oK);g.Q=i$q.prototype;g.Q.qF=function(){this.UD&&em(this,this.UD)};
g.Q.isAvailable=function(){var d;if(d=!!this.cards.length)(d=this.J.getRootNode())?(d=g.Vp(d),d=173<d.width&&173<d.height):d=!1;return d};
g.Q.gR=function(){var d=this.isAvailable();g.dv(this.tA(),d);g.ep(this.context.J.getRootNode(),g.Eo.IV_DRAWER_ENABLED,d);r$(this.J)};
g.Q.destroy=function(){this.J.sJ(!1);try{this.J.getRootNode().removeChild(this.T)}catch(d){}g.lI(this.lr);g.jX(this.RU);this.qk&&this.qk.dispose();this.X&&this.X.dispose();oK.prototype.destroy.call(this)};
g.Q.R1=function(){var d=this;this.context.G.listen(g.bY("iv-drawer-close-button",this.T),"click",this.hG,this);this.context.G.listen(this.U,"touchend",function(){d.rO.start()});
this.context.G.listen(this.U,"scroll",this.OA,this);this.context.U.subscribe("onHideControls",function(){d.aU=!0});
this.context.U.subscribe("onShowControls",function(){d.aU=!1});
this.context.U.subscribe("onVideoAreaChange",function(){d.aU=g.V5(d.J.getRootNode(),"ytp-autohide")});
this.lr.push(g.ST("iv-button-shown",this.Wc,this));this.lr.push(g.ST("iv-button-hidden",this.g6,this));VEc(this)};
g.Q.findLastIndex=function(d){if(this.cards.length===0)return 0;var q=g.Mx(this.cards,function(T){return d.mj.startMs>T.mj.startMs||d.mj.startMs===T.mj.startMs&&d.mj.timestamp>=T.mj.timestamp?!0:!1});
return q===-1?0:q+1};
g.Q.hG=function(){if(this.j){$F(this.context.logger,XB(this).tq.close);var d=g.Q0();d&&this.B&&g.dx(d,this.B);T9(this)}};
g.Q.OA=function(){g.ep(this.T,"iv-drawer-scrolled",this.U.scrollTop>0)};
g.Q.Wc=function(){var d=g.Q0(),q=XB(this);q=q?q.BA:this.BA;d&&q&&g.o$(d,[q])};
g.Q.g6=function(){var d=g.Q0(),q=XB(this);q=q?q.BA:this.BA;d&&q&&g.V0(d,[q])};
g.Q.l2=function(){var d=XB(this);$F(this.context.logger,d.tq.I2);var q=g.Q0();if(q&&d)if(this.J.N("web_infocards_teaser_show_logging_fix")){var T=[];d.Zc&&T.push(d.Zc);d.BA&&T.push(d.BA);T.length>0&&g.o$(q,T)}else g.o$(q,[d.Zc,d.BA])};
g.Q.Bc=function(){var d=g.Q0(),q=XB(this);d&&q&&g.V0(d,[q.Zc])};
g.Q.fF=function(d){var q=XB(this),T=g.Q0();this.G?d?(d=this.context.logger,$F(d,q.tq.hw),d.J.sendVideoStatsEngageEvent(4,void 0),T&&q.Zc&&g.dx(T,q.Zc)):(d=this.context.logger,$F(d,q.tq.hw),d.J.sendVideoStatsEngageEvent(4,void 0),T&&q.BA&&g.dx(T,q.BA)):(d=this.context.logger,$F(d,q.tq.hw),d.J.sendVideoStatsEngageEvent(4,void 0),T&&this.BA&&g.dx(T,this.BA))};g.M(J2,oK);J2.prototype.Py=function(){oK.prototype.Py.call(this);b2E(this)};
J2.prototype.show=function(){oK.prototype.show.call(this);var d=g.Q0(),q=this.annotation.data;d&&q&&(q=q.session_data)&&g.o$(d,[g.y0(q.itct)])};
J2.prototype.hide=function(){oK.prototype.hide.call(this);var d=g.Q0(),q=this.annotation.data;d&&q&&(q=q.session_data)&&g.V0(d,[g.y0(q.itct)])};g.M(sh,J2);
sh.prototype.show=function(){if(!this.isActive){J2.prototype.show.call(this);if(!this.L){g.d9(this.tA(),"iv-branding");var d=this.annotation.data;this.U=this.createElement({Y:"img",hF:["branding-img","iv-click-target"],Z:{"aria-label":"Channel watermark",src:d.image_url,width:d.image_width,height:d.image_height}});g.dv(this.U,!1);var q=this.createElement({Y:"button",hF:["branding-img-container","ytp-button"]});q.appendChild(this.U);this.tA().appendChild(q);var T=this.annotation.Hl();T&&Vs(this,q,
T,this.annotation.id,d.session_data);this.context.J.N("disable_branding_context")||$AB(this,d);this.L=!0}g.dv(this.tA(),!0);this.isActive=!0;if(this.U){try{XVn(this,this.U)}catch(Y){}g.d9(this.context.J.getRootNode(),"ytp-branding-shown");this.context.J.getRootNode().style.setProperty("--branding-image-width",this.U.getAttribute("width")+"px")}}};
sh.prototype.hide=function(){this.isActive&&(J2.prototype.hide.call(this),g.dv(this.tA(),!1),this.isActive=!1,g.TR(this.context.J.getRootNode(),"ytp-branding-shown"))};
sh.prototype.destroy=function(){this.G&&(this.G.dispose(),this.G=null);g.TR(this.context.J.getRootNode(),"ytp-branding-shown");J2.prototype.destroy.call(this)};g.M(Fgl,J2);g.Q=Fgl.prototype;g.Q.show=function(){this.isActive||(J2.prototype.show.call(this),this.K||(RZ_(this),this.K=!0),g.dv(this.tA(),!0),g.GB(function(){g.TR(this.tA(),"iv-promo-inactive")},100,this),this.tA().removeAttribute("aria-hidden"),this.isActive=!0,H2L(this),xAE(this),yIL(this,this.X))};
g.Q.hide=function(){this.isActive&&(g.d9(this.tA(),"iv-promo-inactive"),this.isActive=!1,this.tA().setAttribute("aria-hidden","true"))};
g.Q.CP=function(d,q,T,Y,e,U){return this.isCollapsed?!1:J2.prototype.CP.call(this,d,q,T,Y,e,U)};
g.Q.NE=function(d){this.B=!0;N2q(this,500,d)};
g.Q.nI=function(){this.B=!1;hZL(this)};
g.Q.qE=function(d){d.stopPropagation();this.hide()};
g.Q.mC=function(d){d.stopPropagation();H2L(this);this.isCollapsed=!0;g.d9(this.tA(),"iv-promo-collapsed-no-delay");this.S.start()};
g.Q.destroy=function(){this.S.dispose();J2.prototype.destroy.call(this)};g.M(Mss,g.na);g.Q=Mss.prototype;g.Q.Vg=function(d,q){if(!LgI(this.player.C().playerStyle))return null;switch(d){case "loadCustomAnnotationsXml":return(d=g.dA(q))&&AI7(this,d),!0;case "removeCustomAnnotationById":return q&&this.G&&(lY_(this.G,q),r$(this.player)),!0}return null};
g.Q.getOptions=function(){return LgI(this.player.C().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.Q.GB=function(){var d=this.player.C(),q=this.player.getVideoData(),T=d.annotationsLoadPolicy||q.annotationsLoadPolicy;return q.kc||this.player.isMutedByEmbedsMutedAutoplay()?!1:T===1&&!q.us||d.aU.get(q.videoId)||g.Y4(q)||g.UF(q)?!0:!1};
g.Q.gF=function(){if(this.j){var d=this.player.OD().getVideoContentRect(!0);g.or(this.j.element,d.width,d.height);g.mZ(this.j.element,d.left,d.top)}if(this.G){var q=this.player.Xb();d=this.G;q=q.width;g.ep(d.T,"iv-drawer-small",q<=426);g.ep(d.T,"iv-drawer-big",q>=1280)}};
g.Q.Ut=function(d){EJ7(this,d.state);g.I(d.state,2)&&(this.Tv()&&this.D7()&&this.player.getPresentingPlayerType()!==2&&this.H6(!1),this.sJ(!1))};
g.Q.load=function(){function d(b){var J=q.loadNumber;q.S=null;q.loaded&&q.loadNumber===J&&q.player.getVideoData().videoId===Y&&(b=g.Jd(b)&&b.responseXML?b.responseXML:null)&&(AI7(q,b),g.d9(q.player.getRootNode(),"iv-module-loaded"))}
var q=this;g.na.prototype.load.call(this);EJ7(this,this.player.getPlayerStateObject());this.loadNumber++;var T=this.player.getVideoData(),Y=T.videoId;g.m2()&&(d=pV7(this,d));var e={format:"XML",onFinish:d,onError:function(){q.S=null},
urlParams:{}};T.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var U=this.player.C().aU.get(Y);U&&Z2I(e,U);U=U&&(U.YR||U.cQ);if(!T.H9||U)T.RU?jlB(this,T.RU,e):(this.L=function(){if(!q.B)q.onVideoDataChange(e);var b=q.player.getVideoData();(b==null?0:g.TJ(b))&&!q.lr&&ts7(q,b)},this.player.addEventListener("videodatachange",this.L));
g.o6(this.player,this.j.element,4);this.gF();(U=g.Y4(T))&&rIn(this,U);(U=g.UF(T))&&U.featuredChannel&&Gg7(this,U.featuredChannel,U.annotationId||"branding",T.videoId||null,T.eventId||null);this.x9=g.bY("ytp-cards-button",this.player.getRootNode());g.TJ(T)&&ts7(this,T)};
g.Q.onVideoDataChange=function(d){var q=this.player.getVideoData();q.RU&&jlB(this,q.RU,d)};
g.Q.unload=function(){this.player.hm("annotations_module");for(var d=g.E(Object.keys(this.X)),q=d.next();!q.done;q=d.next())this.X[q.value].destroy();this.K=null;this.G&&(this.G.destroy(),this.G=null,r$(this.player));this.B=!1;this.S&&(this.S.abort(),this.S=null);this.lr=!1;this.X={};this.U.hide();g.na.prototype.unload.call(this);this.j.detach();this.L&&(this.player.removeEventListener("videodatachange",this.L),this.L=null)};
g.Q.JK=function(d){d===this.player.getVideoData().videoId&&(this.loaded?O2B(this):this.load())};
g.Q.Tv=function(){var d;return((d=this.G)==null?void 0:d.isAvailable())||this.lr};
g.Q.D7=function(){return!!this.G&&this.G.j};
g.Q.H6=function(d,q,T){q=q===void 0?!1:q;this.Tv();this.G&&(d?T?q2(this.G,T,q):q2(this.G,"YOUTUBE_DRAWER_AUTO_OPEN",q):T9(this.G))};
g.Q.sJ=function(d,q){this.player.publish(d?"cardsteasershow":"cardsteaserhide",q)};
g.Q.ir=function(){this.player.C().aU.unsubscribe("vast_info_card_add",this.JK,this);g.TR(this.player.getRootNode(),g.Eo.IV_DRAWER_OPEN);for(var d=this.UD,q=g.Gh,T=0,Y=d.length;T<Y;T++)q.Qt(d[T]);this.UD.length=0;g.na.prototype.ir.call(this)};
g.Q.createElement=function(d){d=new g.f(d);g.C(this,d);return d.element};g.Oi("annotations_module",Mss);g.Oi("creatorendscreen",xbN);})(_yt_player);
