(function(g){var window=this;'use strict';var U8R=function(d){d.publish("autonavvisibility")},bFN=function(d,q){d.gO("onAutonavCoundownStarted",q)},X5_=function(d){var q,T,Y;
return d==null?void 0:(q=d.playerOverlays)==null?void 0:(T=q.playerOverlayRenderer)==null?void 0:(Y=T.autoplay)==null?void 0:Y.playerOverlayAutoplayRenderer},bT=function(d){var q=d.C(),T=q.T;
g.f.call(this,{Y:"a",D:"ytp-autonav-suggestion-card",Z:{href:"{{url}}",target:T?q.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{Y:"div",hF:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Z:{style:"{{background}}"},V:[{Y:"div",Z:{"aria-label":"{{timestamp}}"},hF:["ytp-autonav-timestamp"],j5:"{{duration}}"},{Y:"div",hF:["ytp-autonav-live-stamp"],j5:"Live"},{Y:"div",
hF:["ytp-autonav-upcoming-stamp"],j5:"Upcoming"},{Y:"div",D:"ytp-autonav-list-overlay",V:[{Y:"div",D:"ytp-autonav-mix-text",j5:"Mix"},{Y:"div",D:"ytp-autonav-mix-icon"}]}]},{Y:"div",hF:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],j5:"{{title}}"},{Y:"div",hF:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],j5:"{{author}}"},{Y:"div",hF:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],j5:"{{views_and_publish_time}}"}]});this.J=d;this.suggestion=
null;this.G=T;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},Xd=function(d,q){q=q===void 0?!1:q;
g.f.call(this,{Y:"div",D:"ytp-autonav-endscreen-countdown-overlay"});var T=this;this.L=q;this.cancelCommand=this.X=void 0;this.j=0;this.container=new g.f({Y:"div",D:"ytp-autonav-endscreen-countdown-container"});g.C(this,this.container);this.container.IU(this.element);q=d.C();var Y=q.T;this.J=d;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.W(d,"videodatachange",this.onVideoDataChange);this.G=new g.f({Y:"div",D:"ytp-autonav-endscreen-upnext-container",Z:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{Y:"div",D:"ytp-autonav-endscreen-upnext-header"},{Y:"div",D:"ytp-autonav-endscreen-upnext-alternative-header",j5:"{{autoplayAlternativeHeader}}"},{Y:"a",D:"ytp-autonav-endscreen-link-container",Z:{href:"{{url}}",target:Y?q.K:""},V:[{Y:"div",D:"ytp-autonav-endscreen-upnext-thumbnail",Z:{style:"{{background}}"},V:[{Y:"div",Z:{"aria-label":"{{timestamp}}"},hF:["ytp-autonav-timestamp"],
j5:"{{duration}}"},{Y:"div",hF:["ytp-autonav-live-stamp"],j5:"Live"},{Y:"div",hF:["ytp-autonav-upcoming-stamp"],j5:"Upcoming"}]},{Y:"div",D:"ytp-autonav-endscreen-video-info",V:[{Y:"div",D:"ytp-autonav-endscreen-premium-badge"},{Y:"div",D:"ytp-autonav-endscreen-upnext-title",j5:"{{title}}"},{Y:"div",D:"ytp-autonav-endscreen-upnext-author",j5:"{{author}}"},{Y:"div",D:"ytp-autonav-view-and-date",j5:"{{views_and_publish_time}}"},{Y:"div",D:"ytp-autonav-author-and-view",j5:"{{author_and_views}}"}]}]}]});
g.C(this,this.G);this.G.IU(this.container.element);Y||this.W(this.G.Qv("ytp-autonav-endscreen-link-container"),"click",this.bP);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.G.Qv("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.f({Y:"div",D:"ytp-autonav-overlay"});g.C(this,this.overlay);this.overlay.IU(this.container.element);this.U=new g.f({Y:"div",D:"ytp-autonav-endscreen-button-container"});g.C(this,this.U);this.U.IU(this.container.element);
this.cancelButton=new g.f({Y:"button",hF:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",q.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Z:{"aria-label":"Cancel autoplay"},j5:"Cancel"});g.C(this,this.cancelButton);this.cancelButton.IU(this.U.element);this.cancelButton.listen("click",this.z1,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.f({Y:"a",hF:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
q.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Z:{href:"{{url}}",role:"button","aria-label":"Play next video"},j5:"Play Now"});g.C(this,this.playButton);this.playButton.IU(this.U.element);this.playButton.listen("click",this.bP,this);this.J.createServerVe(this.playButton.element,this.playButton,!0);(q=this.J.getVideoData())&&Jyx(this,q);this.T=new g.f9(function(){sO7(T)},500);
g.C(this,this.T);this.hH();this.W(d,"autonavvisibility",this.hH);this.J.N("web_autonav_color_transition")&&(this.W(d,"autonavchange",this.Mb),this.W(d,"onAutonavCoundownStarted",this.SDZ))},J9=function(d){var q=d.J.Xb(!0,d.J.isFullscreen());
g.ep(d.container.element,"ytp-autonav-endscreen-small-mode",d.Rl(q));g.ep(d.container.element,"ytp-autonav-endscreen-is-premium",!!d.suggestion&&!!d.suggestion.Vh5);g.ep(d.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!d.J.yX());g.ep(d.J.getRootNode(),"countdown-running",d.XT());g.ep(d.container.element,"ytp-player-content",d.J.yX());g.Dv(d.overlay.element,{width:q.width+"px"});if(!d.XT()){d.J.yX()?$8Q(d,Math.round(gtN(d)/1E3)):$8Q(d);q=!!d.suggestion&&!!d.suggestion.yh;var T=d.J.yX()||
!q;g.ep(d.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!T&&q);g.ep(d.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",T&&!q);d.U.OM(d.J.yX());g.ep(d.element,"ytp-enable-w2w-color-transitions",FvQ(d))}},sO7=function(d){var q=gtN(d),T=Math,Y=T.min;
var e=d.j?Date.now()-d.j:0;T=Y.call(T,e,q);$8Q(d,Math.ceil((q-T)/1E3));q-T<=500&&d.XT()?d.select(!0):d.XT()&&d.T.start()},gtN=function(d){if(d.J.isFullscreen()){var q;
d=(q=d.J.getVideoData())==null?void 0:q.rQ;return d===-1||d===void 0?8E3:d}return d.J.qI()>=0?d.J.qI():g.Yv(d.J.C().experiments,"autoplay_time")||1E4},Jyx=function(d,q){q=q.getWatchNextResponse();
var T,Y;q=(T=X5_(q))==null?void 0:(Y=T.nextButton)==null?void 0:Y.buttonRenderer;d.X=q==null?void 0:q.navigationEndpoint;T=q==null?void 0:q.trackingParams;d.playButton&&T&&d.J.setTrackingParams(d.playButton.element,T)},FvQ=function(d){var q;
return!((q=d.J.getVideoData())==null||!q.watchToWatchTransitionRenderer)},$8Q=function(d,q){q=q===void 0?-1:q;
d=d.G.Qv("ytp-autonav-endscreen-upnext-header");g.xE(d);if(q>=0){q=String(q);var T="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],Y="Up next in $SECONDS".indexOf(T);if(Y>=0){d.appendChild(g.NQ("Up next in $SECONDS".slice(0,Y)));var e=g.FE("span");g.o1(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Qp(e,q);d.appendChild(e);d.appendChild(g.NQ("Up next in $SECONDS".slice(Y+T.length)));return}}g.Qp(d,"Up next")},sZ=function(d,q){g.f.call(this,{Y:"div",
hF:["html5-endscreen","ytp-player-content",q||"base-endscreen"]});this.created=!1;this.player=d},$6=function(d){g.f.call(this,{Y:"div",
hF:["ytp-upnext","ytp-player-content"],Z:{"aria-label":"{{aria_label}}"},V:[{Y:"div",D:"ytp-cued-thumbnail-overlay-image",Z:{style:"{{background}}"}},{Y:"span",D:"ytp-upnext-top",V:[{Y:"span",D:"ytp-upnext-header",j5:"Up Next"},{Y:"span",D:"ytp-upnext-title",j5:"{{title}}"},{Y:"span",D:"ytp-upnext-author",j5:"{{author}}"}]},{Y:"a",D:"ytp-upnext-autoplay-icon",Z:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{Y:"svg",Z:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{Y:"circle",D:"ytp-svg-autoplay-circle",Z:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{Y:"circle",D:"ytp-svg-autoplay-ring",Z:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{Y:"path",D:"ytp-svg-fill",Z:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{Y:"span",D:"ytp-upnext-bottom",V:[{Y:"span",D:"ytp-upnext-cancel"},{Y:"span",D:"ytp-upnext-paused",
j5:"Autoplay is paused"}]}]});this.api=d;this.cancelButton=null;this.X=this.Qv("ytp-svg-autoplay-ring");this.j=this.notification=this.G=this.suggestion=null;this.T=new g.f9(this.wR,5E3,this);this.U=0;var q=this.Qv("ytp-upnext-cancel");this.cancelButton=new g.f({Y:"button",hF:["ytp-upnext-cancel-button","ytp-button"],Z:{tabindex:"0","aria-label":"Cancel autoplay"},j5:"Cancel"});g.C(this,this.cancelButton);this.cancelButton.listen("click",this.pF,this);this.cancelButton.IU(q);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.C(this,this.T);this.api.createClientVe(this.element,this,18788);q=this.Qv("ytp-upnext-autoplay-icon");this.W(q,"click",this.rW);this.api.createClientVe(q,this,115130);this.HM();this.W(d,"autonavvisibility",this.HM);this.W(d,"mdxnowautoplaying",this.hYv);this.W(d,"mdxautoplaycanceled",this.bnx);g.ep(this.element,"ytp-upnext-mobile",this.api.C().U)},NDq=function(d,q){if(q)return q;
if(d.api.isFullscreen()){var T;d=(T=d.api.getVideoData())==null?void 0:T.rQ;return d===-1||d===void 0?8E3:d}return d.api.qI()>=0?d.api.qI():g.Yv(d.api.C().experiments,"autoplay_time")||1E4},RDN=function(d,q){q=NDq(d,q);
var T=Math,Y=T.min;var e=(0,g.cj)()-d.U;T=Y.call(T,e,q);q=q===0?1:Math.min(T/q,1);d.X.setAttribute("stroke-dashoffset",""+-211*(q+1));q>=1&&d.XT()&&d.api.getPresentingPlayerType()!==3?d.select(!0):d.XT()&&d.G.start()},g3=function(d){sZ.call(this,d,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.f({Y:"div",D:"ytp-suggestion-panel",V:[{Y:"div",hF:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],j5:"More videos"}]});this.B=new g.f({Y:"div",D:"ytp-suggestions-container"});this.videos=[];this.j=null;this.X=this.L=!1;this.U=new Xd(this.player);g.C(this,this.U);this.U.IU(this.element);d.getVideoData().gk?this.G=this.U:(this.G=new $6(d),g.o6(this.player,this.G.element,4),g.C(this,this.G));this.overlay=new g.f({Y:"div",
D:"ytp-autonav-overlay-cancelled-state"});g.C(this,this.overlay);this.overlay.IU(this.element);this.T=new g.aI(this);g.C(this,this.T);g.C(this,this.table);this.table.IU(this.element);this.table.show();g.C(this,this.B);this.B.IU(this.table.element);this.hide()},Fd=function(d){var q=d.yX();
q!==d.X&&(d.X=q,U8R(d.player),d.X?(d.U!==d.G&&d.U.hide(),d.table.hide()):(d.U!==d.G&&d.U.show(),d.table.show()))},x8N=function(d){sZ.call(this,d,"videowall-endscreen");
var q=this;this.J=d;this.stills=[];this.j=this.videoData=null;this.T=this.L=!1;this.B=null;g.d9(this.element,"modern-videowall-endscreen");this.U=new g.aI(this);g.C(this,this.U);this.X=new g.f9(function(){g.d9(q.element,"ytp-show-tiles")},0);
g.C(this,this.X);this.table=new g.Ux({Y:"div",D:"ytp-modern-endscreen-content"});g.C(this,this.table);this.table.IU(this.element);d.getVideoData().gk?this.G=new Xd(d,!0):this.G=new $6(d);g.C(this,this.G);g.o6(this.player,this.G.element,4);d.createClientVe(this.element,this,158789);this.hide()},ND=function(d){return g.V2(d.player)&&d.KL()&&!d.j},Rt=function(d){var q=d.yX();
q!==d.L&&(d.L=q,U8R(d.player))},yyQ=function(d){sZ.call(this,d,"subscribecard-endscreen");
this.G=new g.f({Y:"div",D:"ytp-subscribe-card",V:[{Y:"img",D:"ytp-author-image",Z:{src:"{{profilePicture}}"}},{Y:"div",D:"ytp-subscribe-card-right",V:[{Y:"div",D:"ytp-author-name",j5:"{{author}}"},{Y:"div",D:"html5-subscribe-button-container"}]}]});g.C(this,this.G);this.G.IU(this.element);var q=d.getVideoData();this.subscribeButton=new g.Jg("Subscribe",null,"Unsubscribe",null,!0,!1,q.Gp,q.subscribed,"trailer-endscreen",null,d,!1);g.C(this,this.subscribeButton);this.subscribeButton.IU(this.G.Qv("html5-subscribe-button-container"));
this.W(d,"videodatachange",this.S5);this.S5();this.hide()},x6=function(d){var q=d.C(),T=g.MI||g.o9?{style:"will-change: opacity"}:void 0,Y=q.T,e=["ytp-videowall-still"];
q.U&&e.push("ytp-videowall-show-text");g.f.call(this,{Y:"a",hF:e,Z:{href:"{{url}}",target:Y?q.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{Y:"div",D:"ytp-videowall-still-image",Z:{style:"{{background}}"}},{Y:"span",D:"ytp-videowall-still-info",Z:{"aria-hidden":"true"},V:[{Y:"span",D:"ytp-videowall-still-info-bg",V:[{Y:"span",D:"ytp-videowall-still-info-content",Z:T,V:[{Y:"span",D:"ytp-videowall-still-info-title",j5:"{{title}}"},
{Y:"span",D:"ytp-videowall-still-info-author",j5:"{{author_and_views}}"},{Y:"span",D:"ytp-videowall-still-info-live",j5:"Live"},{Y:"span",D:"ytp-videowall-still-info-duration",j5:"{{duration}}"}]}]}]},{Y:"span",hF:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Z:{"aria-hidden":"true"},V:[{Y:"span",D:"ytp-videowall-still-listlabel-icon"},"Playlist",{Y:"span",D:"ytp-videowall-still-listlabel-length",V:[" (",{Y:"span",j5:"{{playlist_length}}"},")"]}]},{Y:"span",hF:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],Z:{"aria-hidden":"true"},V:[{Y:"span",D:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{Y:"span",D:"ytp-videowall-still-listlabel-length",j5:" (50+)"}]}]});this.suggestion=null;this.U=Y;this.api=d;this.G=new g.aI(this);g.C(this,this.G);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.G.W(d,"videodatachange",this.onVideoDataChange);d.createServerVe(this.element,this);this.onVideoDataChange()},yJ=function(d){sZ.call(this,d,"videowall-endscreen");
var q=this;this.J=d;this.j=0;this.stills=[];this.T=this.videoData=null;this.X=this.B=!1;this.K=null;this.U=new g.aI(this);g.C(this,this.U);this.L=new g.f9(function(){g.d9(q.element,"ytp-show-tiles")},0);
g.C(this,this.L);var T=new g.f({Y:"button",hF:["ytp-button","ytp-endscreen-previous"],Z:{"aria-label":"Previous"},V:[g.Rh()]});g.C(this,T);T.IU(this.element);T.listen("click",this.u2,this);this.table=new g.Ux({Y:"div",D:"ytp-endscreen-content"});g.C(this,this.table);this.table.IU(this.element);T=new g.f({Y:"button",hF:["ytp-button","ytp-endscreen-next"],Z:{"aria-label":"Next"},V:[g.xP()]});g.C(this,T);T.IU(this.element);T.listen("click",this.HX,this);d.getVideoData().gk?this.G=new Xd(d,!0):this.G=
new $6(d);g.C(this,this.G);g.o6(this.player,this.G.element,4);d.createClientVe(this.element,this,158789);this.hide()},h9=function(d){return g.V2(d.player)&&d.KL()&&!d.T},HC=function(d){var q=d.yX();
q!==d.B&&(d.B=q,U8R(d.player))},hDn=function(d,q){g.f.call(this,{Y:"button",
hF:["ytp-watch-on-youtube-button","ytp-button"],j5:"{{content}}"});this.J=d;this.buttonType=this.buttonType=q;this.An();this.buttonType===2&&g.d9(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.An);this.OM(!0)},QJ=function(d){sZ.call(this,d,"watch-again-on-youtube-endscreen");
this.watchButton=new hDn(d,1);g.C(this,this.watchButton);this.watchButton.IU(this.element);g.YIn(d)&&(this.G=new g.To(d),g.C(this,this.G),this.U=new g.f({Y:"div",hF:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Z:{tabIndex:"-1"},V:[this.G]}),g.C(this,this.U),this.G.IU(this.U.element),this.U.IU(this.element));d.createClientVe(this.element,this,156914);this.hide()},cyR=function(d){g.na.call(this,d);
var q=this;this.endScreen=null;this.G=this.U=this.j=!1;this.listeners=new g.aI(this);g.C(this,this.listeners);var T=d.C();d.isEmbedsShortsMode()?this.endScreen=new QJ(d):HFR(d)?(this.j=!0,QOQ(this),this.G?this.endScreen=new g3(d):T.N("delhi_modern_endscreen")?this.endScreen=new x8N(d):this.endScreen=new yJ(d)):T.Kz?this.endScreen=new yyQ(d):this.endScreen=new sZ(d);g.C(this,this.endScreen);g.o6(d,this.endScreen.element,4);M9l(this);this.listeners.W(d,"videodatachange",this.onVideoDataChange,this);
this.listeners.W(d,g.Sh("endscreen"),function(Y){q.onCueRangeEnter(Y)});
this.listeners.W(d,g.lG("endscreen"),function(Y){q.onCueRangeExit(Y)})},QOQ=function(d){var q=d.player.getVideoData();
if(!q||d.G===q.l9&&d.U===q.gk)return!1;d.G=q.l9;d.U=q.gk;return!0},HFR=function(d){d=d.C();
return d.LC&&!d.Kz&&!d.disableOrganicUi},M9l=function(d){d.player.hm("endscreen");
var q=d.player.getVideoData();q=new g.Ij(Math.max((q.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var T=new g.Ij(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});d.player.ES([q,T])};
g.fV.prototype.qI=g.eD(6,function(){return this.app.qI()});
g.c1.prototype.qI=g.eD(5,function(){return this.getVideoData().YY});
g.CV.prototype.RV=g.eD(4,function(d){this.u1().RV(d)});
g.ql.prototype.RV=g.eD(3,function(d){this.N6!==d&&(this.N6=d,this.zB())});
g.M(bT,g.f);bT.prototype.select=function(){this.J.tC(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.qq||void 0)&&this.J.logClick(this.element)};
bT.prototype.onClick=function(d){g.AM(d,this.J,this.G,this.suggestion.sessionData||void 0)&&this.select()};
bT.prototype.onKeyPress=function(d){switch(d.keyCode){case 13:case 32:d.defaultPrevented||(this.select(),d.preventDefault())}};g.M(Xd,g.f);g.Q=Xd.prototype;g.Q.HD=function(d){this.suggestion!==d&&(this.suggestion=d,g.xr(this.G,d),this.playButton.updateValue("url",this.suggestion.Xk()),J9(this))};
g.Q.XT=function(){return this.j>0};
g.Q.Vm=function(){this.XT()||(this.j=Date.now(),sO7(this),bFN(this.J,gtN(this)),g.ep(this.J.getRootNode(),"countdown-running",this.XT()))};
g.Q.nt=function(){this.h8();sO7(this);var d=this.G.Qv("ytp-autonav-endscreen-upnext-header");d&&g.Qp(d,"Up next")};
g.Q.h8=function(){this.XT()&&(this.T.stop(),this.j=0)};
g.Q.select=function(d){this.J.nextVideo(!1,d===void 0?!1:d);this.h8()};
g.Q.bP=function(d){g.AM(d,this.J)&&(d.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):d.currentTarget===this.G.Qv("ytp-autonav-endscreen-link-container")&&(d=this.G.Qv("ytp-autonav-endscreen-link-container"),this.J.logVisibility(d,!0),this.J.logClick(d)),this.X?(this.J.gO("innertubeCommand",this.X),this.h8()):this.select())};
g.Q.z1=function(){this.J.logClick(this.cancelButton.element);g.iH(this.J,!0);this.cancelCommand&&this.J.gO("innertubeCommand",this.cancelCommand)};
g.Q.onVideoDataChange=function(d,q){Jyx(this,q);d=q.getWatchNextResponse();var T,Y;d=(T=X5_(d))==null?void 0:(Y=T.cancelButton)==null?void 0:Y.buttonRenderer;this.cancelCommand=d==null?void 0:d.command};
g.Q.SDZ=function(d){if(FvQ(this)){var q=this.J.getVideoData().watchToWatchTransitionRenderer,T=q==null?void 0:q.fromColorPaletteDark;q=q==null?void 0:q.toColorPaletteDark;if(T&&q){var Y=this.element;Y.style.setProperty("--w2w-start-background-color",g.Gc(T.surgeColor));Y.style.setProperty("--w2w-start-primary-text-color",g.Gc(T.primaryTitleColor));Y.style.setProperty("--w2w-start-secondary-text-color",g.Gc(T.secondaryTitleColor));Y.style.setProperty("--w2w-end-background-color",g.Gc(q.surgeColor));
Y.style.setProperty("--w2w-end-primary-text-color",g.Gc(q.primaryTitleColor));Y.style.setProperty("--w2w-end-secondary-text-color",g.Gc(q.secondaryTitleColor));Y.style.setProperty("--w2w-animation-duration",d+"ms")}g.ep(this.element,"ytp-w2w-animate",!0)}};
g.Q.Mb=function(d){this.J.N("web_autonav_color_transition")&&d!==2&&g.ep(this.element,"ytp-w2w-animate",!1)};
g.Q.hH=function(){var d=this.J.yX();this.L&&this.PF!==d&&this.OM(d);J9(this);this.J.logVisibility(this.container.element,d);this.J.logVisibility(this.cancelButton.element,d);this.J.logVisibility(this.G.Qv("ytp-autonav-endscreen-link-container"),d);this.J.logVisibility(this.playButton.element,d)};
g.Q.Rl=function(d){return d.width<400||d.height<459};g.M(sZ,g.f);g.Q=sZ.prototype;g.Q.create=function(){this.created=!0};
g.Q.destroy=function(){this.created=!1};
g.Q.KL=function(){return!1};
g.Q.yX=function(){return!1};
g.Q.TY=function(){return!1};g.M($6,g.f);g.Q=$6.prototype;g.Q.wR=function(){this.notification&&(this.T.stop(),this.t1(this.j),this.j=null,this.notification.close(),this.notification=null)};
g.Q.HD=function(d){this.suggestion=d;g.xr(this,d,"hqdefault.jpg")};
g.Q.HM=function(){this.OM(this.api.yX());this.api.logVisibility(this.element,this.api.yX());this.api.logVisibility(this.Qv("ytp-upnext-autoplay-icon"),this.api.yX());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.yX())};
g.Q.JAD=function(){window.focus();this.wR()};
g.Q.Vm=function(d){var q=this;this.XT()||(g.vW("a11y-announce","Up Next "+this.suggestion.title),this.U=(0,g.cj)(),this.G=new g.f9(function(){RDN(q,d)},25),RDN(this,d),bFN(this.api,NDq(this,d)));
g.TR(this.element,"ytp-upnext-autoplay-paused")};
g.Q.hide=function(){g.f.prototype.hide.call(this)};
g.Q.XT=function(){return!!this.G};
g.Q.nt=function(){this.h8();this.U=(0,g.cj)();RDN(this);g.d9(this.element,"ytp-upnext-autoplay-paused")};
g.Q.h8=function(){this.XT()&&(this.G.dispose(),this.G=null)};
g.Q.select=function(d){d=d===void 0?!1:d;if(this.api.C().N("autonav_notifications")&&d&&window.Notification&&typeof document.hasFocus==="function"){var q=Notification.permission;q==="default"?Notification.requestPermission():q!=="granted"||document.hasFocus()||(this.wR(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Qg()}),this.j=this.W(this.notification,"click",this.JAD),this.T.start())}this.h8();this.api.nextVideo(!1,d)};
g.Q.rW=function(d){!g.HB(this.cancelButton.element,d.target)&&g.AM(d,this.api)&&(this.api.yX()&&this.api.logClick(this.Qv("ytp-upnext-autoplay-icon")),this.select())};
g.Q.pF=function(){this.api.yX()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.iH(this.api,!0)};
g.Q.hYv=function(d){this.api.getPresentingPlayerType();this.show();this.Vm(d)};
g.Q.bnx=function(){this.api.getPresentingPlayerType();this.h8();this.hide()};
g.Q.ir=function(){this.h8();this.wR();g.f.prototype.ir.call(this)};g.M(g3,sZ);g.Q=g3.prototype;g.Q.create=function(){sZ.prototype.create.call(this);this.T.W(this.player,"appresize",this.sK);this.T.W(this.player,"onVideoAreaChange",this.sK);this.T.W(this.player,"videodatachange",this.onVideoDataChange);this.T.W(this.player,"autonavchange",this.uP);this.T.W(this.player,"onAutonavCancelled",this.Iz);this.onVideoDataChange()};
g.Q.show=function(){sZ.prototype.show.call(this);(this.L||this.j&&this.j!==this.videoData.clientPlaybackNonce)&&g.iH(this.player,!1);g.V2(this.player)&&this.KL()&&!this.j?(Fd(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.G.select(!0):this.G.Vm():this.videoData.autonavState===3&&this.G.nt()):(g.iH(this.player,!0),Fd(this));this.sK()};
g.Q.hide=function(){sZ.prototype.hide.call(this);this.G.nt();Fd(this)};
g.Q.sK=function(){var d=this.player.Xb(!0,this.player.isFullscreen());Fd(this);J9(this.U);g.ep(this.element,"ytp-autonav-cancelled-small-mode",this.Rl(d));g.ep(this.element,"ytp-autonav-cancelled-tiny-mode",this.nO(d));g.ep(this.element,"ytp-autonav-cancelled-mini-mode",d.width<=400||d.height<=360);this.overlay&&g.Dv(this.overlay.element,{width:d.width+"px"});if(!this.X)for(d=0;d<this.videos.length;d++)g.ep(this.videos[d].element,"ytp-suggestion-card-with-margin",d%2===1)};
g.Q.onVideoDataChange=function(){var d=this.player.getVideoData();if(this.videoData!==d&&d){this.videoData=d;if((d=this.videoData.suggestions)&&d.length||this.player.N("web_player_autonav_empty_suggestions_fix")){var q=g.jH(this.videoData);q&&(this.G.HD(q),this.G!==this.U&&this.U.HD(q))}if(d&&d.length)for(q=0;q<EtN.length;++q){var T=EtN[q];if(d&&d[T]){this.videos[q]=new bT(this.player);var Y=this.videos[q];T=d[T];Y.suggestion!==T&&(Y.suggestion=T,g.xr(Y,T));g.C(this,this.videos[q]);this.videos[q].IU(this.B.element)}}this.sK()}};
g.Q.uP=function(d){d===1?(this.L=!1,this.j=this.videoData.clientPlaybackNonce,this.G.h8(),this.PF&&this.sK()):(this.L=!0,this.yX()&&(d===2?this.G.Vm():d===3&&this.G.nt()))};
g.Q.Iz=function(d){d?this.uP(1):(this.j=null,this.L=!1)};
g.Q.KL=function(){return this.videoData.autonavState!==1};
g.Q.Rl=function(d){return(d.width<910||d.height<459)&&!this.nO(d)&&!(d.width<=400||d.height<=360)};
g.Q.nO=function(d){return d.width<800&&!(d.width<=400||d.height<=360)};
g.Q.yX=function(){return this.PF&&g.V2(this.player)&&this.KL()&&!this.j};
var EtN=[1,3,2,4];g.M(x8N,sZ);g.Q=x8N.prototype;g.Q.create=function(){sZ.prototype.create.call(this);var d=this.player.getVideoData();d&&(this.videoData=d);this.bT();this.U.W(this.player,"appresize",this.bT);this.U.W(this.player,"onVideoAreaChange",this.bT);this.U.W(this.player,"videodatachange",this.onVideoDataChange);this.U.W(this.player,"autonavchange",this.KP);this.U.W(this.player,"onAutonavCancelled",this.YS);d=this.videoData.autonavState;d!==this.B&&this.KP(d);this.U.W(this.element,"transitionend",this.hx)};
g.Q.destroy=function(){g.jX(this.U);g.Yt(this.stills);this.stills=[];sZ.prototype.destroy.call(this);g.TR(this.element,"ytp-show-tiles");this.X.stop();this.B=this.videoData.autonavState};
g.Q.KL=function(){return this.videoData.autonavState!==1};
g.Q.show=function(){var d=this.PF;sZ.prototype.show.call(this);g.TR(this.element,"ytp-show-tiles");this.player.C().U?g.ic(this.X):this.X.start();(this.T||this.j&&this.j!==this.videoData.clientPlaybackNonce)&&g.iH(this.player,!1);ND(this)?(Rt(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.G.select(!0):this.G.Vm():this.videoData.autonavState===3&&this.G.nt()):(g.iH(this.player,!0),Rt(this));d!==this.PF&&this.player.logVisibility(this.element,!0)};
g.Q.hide=function(){var d=this.PF;sZ.prototype.hide.call(this);this.G.nt();Rt(this);d!==this.PF&&this.player.logVisibility(this.element,!1)};
g.Q.hx=function(d){d.target===this.element&&this.bT()};
g.Q.bT=function(){var d,q,T,Y;var e=((d=this.videoData)==null?0:(q=d.suggestions)==null?0:q.length)?(T=this.videoData)==null?void 0:T.suggestions:[(Y=this.videoData)==null?void 0:g.jH(Y)];if(e.length){q=this.J.Xb(!0,this.J.isFullscreen());d=Math.floor((q.width-64+16)/(g.Cn(q.width*.27,250,450)+16));q=Math.min(3,Math.floor((q.height-64)/((q.width-64-(d-1)*16)/d*.5625+70)));g.YG(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.d9(this.element,"ytp-modern-endscreen-limit-rows-"+q);g.ep(this.element,"ytp-modern-endscreen-single-item",d===1);g.ep(this.element,"ytp-modern-endscreen-row-0",q===0);d=this.table.element;d.ariaLive="polite";this.G.HD(g.jH(this.videoData));this.G instanceof Xd&&J9(this.G);g.ep(this.element,"ytp-endscreen-takeover",ND(this));Rt(this);q=0;d.ariaBusy="true";T=e.length;for(Y=0;Y<T;Y++){var U=Y%T,b=this.stills[Y];b||(b=new g.yV(this.player),this.stills[Y]=b,d.appendChild(b.element));g.sUj(b,e[U]);q++}this.stills.length=
q}};
g.Q.onVideoDataChange=function(){var d=this.player.getVideoData(1);this.videoData!==d&&(d!=null&&g.jH(d)?(this.videoData=d,this.bT()):this.player.oU("missg",{vid:(d==null?void 0:d.videoId)||"",cpn:(d==null?void 0:d.clientPlaybackNonce)||""}))};
g.Q.TY=function(){return this.G.XT()};
g.Q.KP=function(d){d===1?(this.T=!1,this.j=this.videoData.clientPlaybackNonce,this.G.h8(),this.PF&&this.bT()):(this.T=!0,this.PF&&ND(this)&&(d===2?this.G.Vm():d===3&&this.G.nt()))};
g.Q.YS=function(d){if(d){for(d=0;d<this.stills.length;d++)this.J.logVisibility(this.stills[d].element,!0);this.KP(1)}else this.j=null,this.T=!1;this.bT()};
g.Q.yX=function(){return this.PF&&ND(this)};g.M(yyQ,sZ);yyQ.prototype.S5=function(){var d=this.player.getVideoData();this.G.update({profilePicture:d.profilePicture,author:d.author});this.subscribeButton.channelId=d.Gp;var q=this.subscribeButton;d.subscribed?q.G():q.U()};g.M(x6,g.f);x6.prototype.select=function(){this.api.tC(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.qq||void 0)&&this.api.logClick(this.element)};
x6.prototype.onClick=function(d){if(g.dn(this.api.C())&&this.api.N("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var q=this.suggestion.Xk(),T={};g.Sf(this.api,T);q=g.y6(q,T);g.pR(q,this.api,d)}else g.AM(d,this.api,this.U,this.suggestion.sessionData||void 0)&&this.select()};
x6.prototype.onKeyPress=function(d){switch(d.keyCode){case 13:case 32:d.defaultPrevented||(this.select(),d.preventDefault())}};
x6.prototype.onVideoDataChange=function(){var d=this.api.getVideoData(),q=this.api.C();this.U=d.kc?!1:q.T};g.M(yJ,sZ);g.Q=yJ.prototype;g.Q.create=function(){sZ.prototype.create.call(this);var d=this.player.getVideoData();d&&(this.videoData=d);this.d3();this.U.W(this.player,"appresize",this.d3);this.U.W(this.player,"onVideoAreaChange",this.d3);this.U.W(this.player,"videodatachange",this.onVideoDataChange);this.U.W(this.player,"autonavchange",this.wY);this.U.W(this.player,"onAutonavCancelled",this.b2);d=this.videoData.autonavState;d!==this.K&&this.wY(d);this.U.W(this.element,"transitionend",this.dW)};
g.Q.destroy=function(){g.jX(this.U);g.Yt(this.stills);this.stills=[];sZ.prototype.destroy.call(this);g.TR(this.element,"ytp-show-tiles");this.L.stop();this.K=this.videoData.autonavState};
g.Q.KL=function(){return this.videoData.autonavState!==1};
g.Q.show=function(){var d=this.PF;sZ.prototype.show.call(this);g.TR(this.element,"ytp-show-tiles");this.player.C().U?g.ic(this.L):this.L.start();(this.X||this.T&&this.T!==this.videoData.clientPlaybackNonce)&&g.iH(this.player,!1);h9(this)?(HC(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.G.select(!0):this.G.Vm():this.videoData.autonavState===3&&this.G.nt()):(g.iH(this.player,!0),HC(this));d!==this.PF&&this.player.logVisibility(this.element,!0)};
g.Q.hide=function(){var d=this.PF;sZ.prototype.hide.call(this);this.G.nt();HC(this);d!==this.PF&&this.player.logVisibility(this.element,!1)};
g.Q.dW=function(d){d.target===this.element&&this.d3()};
g.Q.d3=function(){var d,q,T,Y;var e=((d=this.videoData)==null?0:(q=d.suggestions)==null?0:q.length)?(T=this.videoData)==null?void 0:T.suggestions:[(Y=this.videoData)==null?void 0:g.jH(Y)];if(e.length){g.d9(this.element,"ytp-endscreen-paginate");var U=this.J.Xb(!0,this.J.isFullscreen());if(d=g.KV(this.J))d=d.rU()?48:32,U.width-=d*2;var b=U.width/U.height;Y=96/54;q=d=2;var J=Math.max(U.width/96,2),F=Math.max(U.height/54,2);T=e.length;var N=T*4;for(N-=4;N>0&&(d<J||q<F);){var R=d/2,x=q/2,y=d<=J-2&&N>=
x*4,h=q<=F-2&&N>=R*4;if((R+1)/x*Y/b>b/(R/(x+1)*Y)&&h)N-=R*4,q+=2;else if(y)N-=x*4,d+=2;else if(h)N-=R*4,q+=2;else break}Y=!1;N>=12&&T*4-N<=6&&(q>=4||d>=4)&&(Y=!0);N=d*96;J=q*54;b=N/J<b?U.height/J:U.width/N;b=Math.min(b,2);N=Math.floor(Math.min(U.width,N*b));J=Math.floor(Math.min(U.height,J*b));U=this.table.element;U.ariaLive="polite";g.or(U,N,J);g.Dv(U,{marginLeft:N/-2+"px",marginTop:J/-2+"px"});this.G.HD(g.jH(this.videoData));this.G instanceof Xd&&J9(this.G);g.ep(this.element,"ytp-endscreen-takeover",
h9(this));HC(this);N+=4;J+=4;b=0;U.ariaBusy="true";for(F=0;F<d;F++)for(R=0;R<q;R++)if(x=b,h=0,Y&&F>=d-2&&R>=q-2?h=1:R%2===0&&F%2===0&&(R<2&&F<2?R===0&&F===0&&(h=2):h=2),x=g.u4(x+this.j,T),h!==0){y=this.stills[b];y||(y=new x6(this.player),this.stills[b]=y,U.appendChild(y.element));var H=Math.floor(J*R/q),a=Math.floor(N*F/d),p=Math.floor(J*(R+h)/q)-H-4,t=Math.floor(N*(F+h)/d)-a-4;g.mZ(y.element,a,H);g.or(y.element,t,p);g.Dv(y.element,"transitionDelay",(R+F)/20+"s");g.ep(y.element,"ytp-videowall-still-mini",
h===1);g.ep(y.element,"ytp-videowall-still-large",h>2);h=Math.max(t,p);g.ep(y.element,"ytp-videowall-still-round-large",h>=256);g.ep(y.element,"ytp-videowall-still-round-medium",h>96&&h<256);g.ep(y.element,"ytp-videowall-still-round-small",h<=96);x=e[x];y.suggestion!==x&&(y.suggestion=x,h=y.api.C(),H=g.V5(y.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.xr(y,x,H),g.dn(h)&&!y.api.N("web_player_log_click_before_generating_ve_conversion_params")&&(h=x.Xk(),H={},g.OF(y.api,"addEmbedsConversionTrackingParams",
[H]),h=g.y6(h,H),y.updateValue("url",h)),(x=(x=x.sessionData)&&x.itct)&&y.api.setTrackingParams(y.element,x));b++}U.ariaBusy="false";g.ep(this.element,"ytp-endscreen-paginate",b<T);for(e=this.stills.length-1;e>=b;e--)d=this.stills[e],g.h4(d.element),g.T1(d);this.stills.length=b}};
g.Q.onVideoDataChange=function(){var d=this.player.getVideoData(1);this.videoData!==d&&(d!=null&&g.jH(d)?(this.j=0,this.videoData=d,this.d3()):this.player.oU("missg",{vid:(d==null?void 0:d.videoId)||"",cpn:(d==null?void 0:d.clientPlaybackNonce)||""}))};
g.Q.HX=function(){this.j+=this.stills.length;this.d3()};
g.Q.u2=function(){this.j-=this.stills.length;this.d3()};
g.Q.TY=function(){return this.G.XT()};
g.Q.wY=function(d){d===1?(this.X=!1,this.T=this.videoData.clientPlaybackNonce,this.G.h8(),this.PF&&this.d3()):(this.X=!0,this.PF&&h9(this)&&(d===2?this.G.Vm():d===3&&this.G.nt()))};
g.Q.b2=function(d){if(d){for(d=0;d<this.stills.length;d++)this.J.logVisibility(this.stills[d].element,!0);this.wY(1)}else this.T=null,this.X=!1;this.d3()};
g.Q.yX=function(){return this.PF&&h9(this)};g.M(hDn,g.f);g.Q=hDn.prototype;g.Q.An=function(){switch(this.buttonType){case 1:var d="Watch again on YouTube";var q=156915;break;case 2:d="Continue watching on YouTube";q=156942;break;default:d="Continue watching on YouTube",q=156942}this.update({content:d});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,q)};
g.Q.onClick=function(d){this.J.N("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.pR(this.getVideoUrl(),this.J,d);this.J.N("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.Q.getVideoUrl=function(){var d=!0;switch(this.buttonType){case 1:d=!0;break;case 2:d=!1}d=this.J.getVideoUrl(d,!1,!1,!0);var q=this.J.C();if(g.dn(q)){var T={};g.dn(q)&&g.OF(this.J,"addEmbedsConversionTrackingParams",[T]);d=g.y6(d,T)}return d};
g.Q.logVisibility=function(){this.J.logVisibility(this.element,this.PF&&this.S)};
g.Q.show=function(){g.f.prototype.show.call(this);this.logVisibility()};
g.Q.hide=function(){g.f.prototype.hide.call(this);this.logVisibility()};
g.Q.N5=function(d){g.f.prototype.N5.call(this,d);this.logVisibility()};g.M(QJ,sZ);QJ.prototype.hasSuggestions=function(){var d;return(d=this.G)==null?void 0:d.hasSuggestions()};
QJ.prototype.show=function(){if(this.player.getPlayerState()!==3){sZ.prototype.show.call(this);var d=this.U;if(d){var q=this.G.hasSuggestions();g.ep(this.element,"ytp-shorts-branded-ui",q);q?d.show():d.hide()}var T;(T=g.KV(this.player))==null||T.RV(!0);this.player.logVisibility(this.element,!0);this.watchButton.N5(!0)}};
QJ.prototype.hide=function(){sZ.prototype.hide.call(this);var d;(d=g.KV(this.player))==null||d.RV(!1);this.player.logVisibility(this.element,!1);this.watchButton.N5(!1)};g.M(cyR,g.na);g.Q=cyR.prototype;g.Q.GB=function(){var d=this.player.getVideoData(),q=d.mutedAutoplay&&(d.limitedPlaybackDurationInSeconds>0||d.endSeconds>0||d.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!q)return!0;var T;var Y=!!((d==null?0:g.jH(d))||(d==null?0:(T=d.suggestions)==null?0:T.length));Y=!HFR(this.player)||Y;d=d.B3;T=this.player.yN();return Y&&!d&&!T&&!q};
g.Q.yX=function(){return this.endScreen.yX()};
g.Q.IH=function(){return this.yX()?this.endScreen.TY():!1};
g.Q.ir=function(){this.player.hm("endscreen");g.na.prototype.ir.call(this)};
g.Q.load=function(){var d=this.player.getVideoData();var q=d.transitionEndpointAtEndOfStream;if(q&&q.videoId){var T=this.player.M5().OS.get("heartbeat"),Y=g.jH(d);!Y||q.videoId!==Y.videoId||d.T$?(this.player.tC(q.videoId,void 0,void 0,!0,!0,q),T&&T.O9("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),d=!0):d=!1}else d=!1;d||(g.na.prototype.load.call(this),this.endScreen.show())};
g.Q.unload=function(){g.na.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.Q.onCueRangeEnter=function(d){this.GB()&&(this.endScreen.created||this.endScreen.create(),d.getId()==="load"&&this.load())};
g.Q.onCueRangeExit=function(d){d.getId()==="load"&&this.loaded&&this.unload()};
g.Q.onVideoDataChange=function(){M9l(this);this.j&&QOQ(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.G?this.endScreen=new g3(this.player):this.endScreen=new yJ(this.player),g.C(this,this.endScreen),g.o6(this.player,this.endScreen.element,4))};g.Oi("endscreen",cyR);})(_yt_player);
